### ISSUE TITLE
AutoClicker bug

### ISSUE THREAD

**Issue by iZave** [Nort721/GodsEye-Issues#103]
A bug report/issue report should contain:

1) GodsEye version – 25 BETA
2) Server Version – 1.12.2 Paper
3) ProtocolLib version – 4.5.0
4) It havent written any logs
5) Screen – https://imgur.com/Z25Zpls
6) I have a problem with AutoClicker function when i pressing the left mouse button its gives me typeC violation

**Comment by Nort721** [comment]
Looks like the bug happened to you when you looked at stones, even though I don't have that bug I've changed some stuff it should be fixed now, if not I'll need more info about the problem
