### ISSUE TITLE
PingSpoof False Positive

### ISSUE THREAD

**Issue by ColaIan** [Nort721/GodsEye-Issues#105]
A bug report/issue report should contain:

1) GodsEye version
Build 25 BETA

2) Server Version+Fork
Spigot-1.15.2

3) ProtocolLib version
v.4.5.0

4) A very detailed description of the issue
Currently our server is located in the UK, and our players are mostly located in Asia / (mostly Hong Kong) which has around 300-350ms ping, and the PingSpoof alert often goes off and kicks out my players

**Comment by Nort721** [comment]
Spigot 1.15.2 is not supported yet, the issue currently not valid

**Comment by ColaIan** [comment]
@Nort721 When are you going to support it then? It has been over 2 months since 1.15 was released though, and I have to use it for production on my server 🤷‍♂️

**Comment by Nort721** [comment]
Well we're doing our best, unfortunately, I'm currently super busy with IRL stuff to a point where I wasn't home for the last two weeks, it sucks but like every human, I also have very busy times, I'm making sure to have some more stable schedule with more free time in the near future but still that stuff takes time, I really don't like that state where I bearly have time for the project and believe me if I wouldn't care about this project I was not investing in it so much effort until today
