### ISSUE TITLE
Please upgrade to 1.15.2

### ISSUE THREAD

**Issue by Riiiiiiiiiiiiiiiiiiiiii** [Nort721/GodsEye-Issues#106]
Please upgrade to 1.15.2

thx u

**Comment by Nort721** [comment]
Hey there, thanks for posting the request here but unfortunately due to our terms we won't give attention to your request until it's removed from the reviews section!

**Comment by Riiiiiiiiiiiiiiiiiiiiii** [comment]
It ’s a pity that I will not delete the comment if you just ask for good reviews
Good support will lead to good reviews

**Comment by ColaIan** [comment]
@Nort721 When are you going to support it then? It has been over 2 months since 1.15 was released though, and I have to use it for production on my server 🤷‍♂️

This situation is totally unacceptable, and I'd like to draw attention from you and your team to address it as soon as possible.

**Comment by Nort721** [comment]
> It ’s a pity that I will not delete the comment if you just ask for good reviews
> Good support will lead to good reviews

We don't ask for good reviews, we just ask to report your requests and bug reports to go in the right place, the review section is the last place for them and was never meant to be used for such things



> @Nort721 When are you going to support it then? It has been over 2 months since 1.15 was released though, and I have to use it for production on my server 🤷‍♂️
> 
> This situation is totally unacceptable, and I'd like to draw attention from you and your team to address it as soon as possible.

Well we're doing our best, unfortunately I'm currently super busy with IRL stuff to a point where I wasn't home for the last two weeks, it sucks but like every human, I also have very busy times, I'm making sure to have some more stable schedule with more free time in the near future but still that stuff takes time, I really don't like that state where I bearly have time for the project and believe me if I wouldn't care about this project I was not investing in it so much effort until today

That's my most honest explanation for the delayed updates

**Comment by Nort721** [comment]
working on the support for other users, experimental support is added soon
