### ISSUE TITLE
Impact Client Criticals in "Jump" mode not being detected

### ISSUE THREAD

**Issue by ColaIan** [Nort721/GodsEye-Issues#107]
Tested in your test server:

Client: 1.14.4 Impact
Criticals in "Jump" mode not being detected.

![image](https://user-images.githubusercontent.com/43201383/74440706-781fa200-4ea9-11ea-8110-41aba901b630.png)

**Comment by Nort721** [comment]
Hey, I've tested it and when using Criticals on jump with the impact client the attack is normal and will not be a critical hit, you can know that by seeing that there is not critical hit particle effect when using it, another way I know that is by printing out the damage value done by the attack and seeing that the damage is not higher then a normal Minecraft hit

**Comment by ColaIan** [comment]
Oh okay thanks
