### ISSUE TITLE
InventoryActions/ChestStealer False Positives

### ISSUE THREAD

**Issue by sunzide** [Nort721/GodsEye-Issues#108]
1) Godseye Build 25 Beta
2) 1.8.8 mSpigot (Taco Spigot Fork)
3) ProtocolLib 4.5.0
4) https://i.imgur.com/deuUQAj.png
5) https://i.imgur.com/3YQXOSD.gifv
6) Seems that users will have an issue left-clicking and pressing shift to transfer items from a chest to their inventories. I don't get what is causing this but I disabled the checks. This happens for all of the users on the server and has been irritating, please fix :)

**Comment by Nort721** [comment]
Hey there, it seems like you are using the wrong version of ProtocolLib, please install the correct one from the link on GodsEye's page, the one for 1.8.X - 1.13.X

**Comment by Nort721** [comment]
Ok I found the issue, the fix will be released in the next update
