### ISSUE TITLE
AutoClicker error

### ISSUE THREAD

**Issue by Deejay9** [Nort721/GodsEye-Issues#109]
A bug report/issue report should contain:

1) GodsEye version - 26 BETA
2) Server Version+Fork - 1.8.8 TacoSpigot
3) ProtocolLib version - 4.4.0-SNAPSHOT-b403
4) Server log - https://pastebin.com/whcb28j1
5) We recommend sending a video/screenshot of the issue if possible, so we would be able to fix it faster. - Just used AutoClicker with CPS over 40
6) A very detailed description of the issue - Turn your autoclicker over 40 CPS and just click

**Comment by Nort721** [comment]
Hey, your Pastebin seem to have been removed, can you send a new one?

**Comment by Nort721** [comment]
Most likely have been solved in later versions, closed for lack for info
