### ISSUE TITLE
Error GodEyes

### ISSUE THREAD

**Issue by kaikuroko** [Nort721/GodsEye-Issues#11]
A bug report/issue report should contain:

1) 1.13.2
2) ProtocolLib 4.4.0 version
3) https://pastebin.com/J5e6MuPf
4)--------
5) the server stop and send me that console errors

**Comment by Nort721** [comment]
I am currently investigating the issue, doing some testing with a server I work with, hopefully, will be able to replicate the issue soon and solve it, I will try to keep updating tho

**Comment by Nort721** [comment]
Try updating to the latest version on spigot (also reset your config)

**Comment by kaikuroko** [comment]
its a error with my server i think, in my network i have 1.12 and 1.13.2 spigots, in the 1.12 runs perfectly (i have only one bug with the ac, when you walk in a slab you teleport to below level) thx for your help, i run back to see what I can do

**Comment by Nort721** [comment]
can you try enabling verbose and telling what check you see that gets set off when you are being teleported?

**Comment by kaikuroko** [comment]
fly, and step

**Comment by kaikuroko** [comment]
i disable that checks with no fix, but its not a big problem

**Comment by kaikuroko** [comment]
and this is the last https://pastebin.com/eJrZ3xHv i got on spigot when i update and reset config

**Comment by Nort721** [comment]
This error has nothing to do with GodsEye tho

**Comment by Nort721** [comment]
closing issue since looks like it stopped happening and errors don't how much if you are still having these issues open a new issue and will make sure to do further investigation
