### ISSUE TITLE
False Flag

### ISSUE THREAD

**Issue by Deejay9** [Nort721/GodsEye-Issues#110]
A bug report/issue report should contain:

1) GodsEye version - Lates t
2) Server Version+Fork - Tested on GodsEye test server
3) ProtocolLib version idk
4) Server log - dont have
5) We recommend sending a video/screenshot of the issue if possible, so we would be able to fix it faster. https://prnt.sc/r7egu6
6) A very detailed description of the issue - Try diving in lava

**Comment by Nort721** [comment]
Hopefully fixed!
