### ISSUE TITLE
Bungeecord & MySQL

### ISSUE THREAD

**Issue by twarix** [Nort721/GodsEye-Issues#111]
A bug report/issue report should contain:

Server Version+Fork: N/A
ProtocolLib version: N/A
Server log: N/A
We recommend sending a video/a screenshot of the issue if possible, so we would be able to fix it faster: N/A
A very detailed description of the issue: Maybe add support for MySQL to sync violation within servers. And maybe also add Bungeecord support for the alert messages!

**Comment by Nort721** [comment]
We will probably not add this to GodsEye itself but we may release a free plugin that will make this possible since that can be done with the API

**Comment by Nort721** [comment]
Unfortunatly this feature will not be added to GodsEye but you can use the plugin called GodsEyeSyn by GoodTimes14 to get MySQL support and cross networks alerts

**Comment by Nort721** [comment]
https://www.spigotmc.org/resources/godseyesync-mysql-and-bungeecord-synchronization.78815/?__cf_chl_jschl_tk__=ac853e3ed28247e841ba69893209d0fa46cf62d2-1590907820-0-AeGZhlD0NuF21A_65hmFyAefHUFz4gYIzm2EXKKVWcGOK3JxxAJ1x08KSNXGEsaF3mJDnJxkT2yv5RvfhUYFIG1GPHqqXmXy6PoBN6zswT0mMHwDQhAhlqU7TtOB-4djSOdpuVbfCz0f1d4lj2YTMgCQxgNtgosnWuGpbTTJX7t1oNYEFsJ8gjBM6B3VZzsHtWR2Fb1AltJnOvYcYLQLQPM2XI2GyVWXtekg2PzIRDgqUwIrp3tXJuAM7x0UZB5MsRkKwOxJUnjY3sIj7e9euYntkEsCjr5wvV0-wV4YQ-wCcXE1HqSY8Xrn7YhtoX4XojNDrWEkqRXRvcfe6ySAh5T9V_QQ3R8GjCya8lC4vGyq
