### ISSUE TITLE
JoinEvent NPE

### ISSUE THREAD

**Issue by Azidea** [Nort721/GodsEye-Issues#116]
A bug report/issue report should contain:

1) GodsEye Version: **vBuild 27 Beta**
2) Server Version+Fork: **Paper 1.13.2**
3) ProtocolLib Version: **v4.5.1-SNAPSHOT-b445**
4) Server Log: https://hasteb.in/owaqoqep.sql 
5) We recommend sending a video/screenshot of the issue if possible, so we would be able to fix it faster.
6) A very detailed description of the issue: Any sort of joining prompts NPE.

**Comment by Nort721** [comment]
Since I can't really replicate this error, I did some changes that should fix it, if after next update you're still having this issue, contact me and I will reopen this issue
