### ISSUE TITLE
[GodsEye] Unhandled exception occured in onPacketReceiving(PacketEvent)

### ISSUE THREAD

**Issue by UnknownName404** [Nort721/GodsEye-Issues#117]
A bug report/issue report should contain:

1) GodsEye version (BUILD 27 BETA)
2) Server Version+Fork (1.15.2 Paper version 129)
3) ProtocolLib version (4.5.0)
4) 
```
[17:54:44 ERROR]: [GodsEye] Unhandled exception occured in onPacketReceiving(PacketEvent) for GodsEye
java.lang.ClassCastException: null
>.... [17:54:44 ERROR]: Parameters:
net.minecraft.server.v1_15_R1.PacketPlayInUseEntity@3766d1d3[
a=97622
action=ATTACK
c=<null>
d=<null>
```

The error sometimes occurs when the plugin detects something "BADPACKETS" - "MOVEMENT"
Sorry for my english ^^ i'm french !

**Comment by UnknownName404** [comment]
I also have this mistake that appeared!

[```
18:32:53 ERROR]: Could not pass event BlockMultiPlaceEvent to GodsEye vBuild 27 BETA
java.lang.NullPointerException: null
```

**Comment by Nort721** [comment]
I need the full error log, please use hastebin to send it

**Comment by UnknownName404** [comment]
[https://pastebin.com/UesdNjhu](url)

**Comment by UnknownName404** [comment]
@Nort721

**Comment by Nort721** [comment]
The error should be fixed after latest update if it still appears hit me up about it on discord Nort721#0001, sorry for taking so long to review this I was busy with IRL stuff
