### ISSUE TITLE
GE Problem

### ISSUE THREAD

**Issue by KoopinMain** [Nort721/GodsEye-Issues#120]
1) 28
2) Paper 1.12.2
3) 4.5.0
4) https://pastebin.com/0xCFpXP1 
5) Not screened or recorded
6) Problem when i destroyed blocks and fly with elytras with cheat

**Comment by Nort721** [comment]
The error has been fixed in Build 29 BETA, for elytrafly GodsEye currently does not block that cheat hence why its not mentioned in the blocked hacks list, will may be added in the future though
