### ISSUE TITLE
False flagging type B on teleport to spawn after death

### ISSUE THREAD

**Issue by jackstaak** [Nort721/GodsEye-Issues#123]
A bug report/issue report should contain:

1) GodsEye version: Build 28 BETA
2) Server Version+Fork: Paper 1.8.8
3) ProtocolLib version: 4.5.0
4) Server log: no errors
5) We recommend sending a video/screenshot of the issue if possible, so we would be able to fix it faster: https://prnt.sc/rj1zz1 and the ping of the person: https://prnt.sc/rj20kq
6) A very detailed description of the issue: when a player dies he get teleported back to spawn, godseye is making false flags type B whenever this happens.

**Comment by Nort721** [comment]
Should be fixed now
