### ISSUE TITLE
Fix Jesus in GodsEye. It does not work for WURST 1.7.2

### ISSUE THREAD

**Issue by Birsenberg** [Nort721/GodsEye-Issues#125]
A bug report/issue report should contain:

1) GodsEye Build 29 BETA
2) Paper 1.12.2
3) ProtocolLib 4.4.0
4) Anti-cheat did not write anything at that moment
5) https://youtu.be/itt1awawwMo
6) Jesus check does not work in GodsEye if I use WURST 1.7.2

**Comment by Nort721** [comment]
Jesus check is currently in development and is not activated at the movement
