### ISSUE TITLE
GodsEye Error

### ISSUE THREAD

**Issue by ItzMystic** [Nort721/GodsEye-Issues#126]
A bug report/issue report should contain:

1) 1.8.0
2) 1.8.9
3) Latest
****4) [GodsEye] activation failed!
> [00:30:29 INFO]: [GodsEye] Your GodsEye copy is not activated for an unknown reason, please contact TopRaider or Nort721 for manual activation
> [00:30:29 INFO]: [GodsEye] Disabling GodsEye vBuild 29 BETA
> [00:30:29 INFO]: [GodsEye] has been disabled****

**Comment by Nort721** [comment]
I have activated your copy

**Comment by ItzMystic** [comment]
Thank you so much!
