### ISSUE TITLE
Wrong reason in the logs

### ISSUE THREAD

**Issue by microwin7** [Nort721/GodsEye-Issues#127]
A bug report/issue report should contain:

1) GodsEye 29
2) Server Spigot 1.8.8, fork Gamai (fix line length + block taking an item from gui)
3) ProtocolLib latest Godseye instructions with site spigot
4) https://imgur.com/a/45ysAnD

**Comment by notwilliqm** [comment]
I think you mean that the logs say KICK even though they were BANNED.

**Comment by microwin7** [comment]
Yes

**Comment by Nort721** [comment]
Damn, I don't understand how this mistake happened, thanks for your report!
