### ISSUE TITLE
Error Console

### ISSUE THREAD

**Issue by DaffyDG** [Nort721/GodsEye-Issues#129]
GodsEye 29
Server [1.8.8] ImanitySpigot | Asynchronous server and worlds | Cave 6.0 settings
ProtocolLib latest Godseye instructions with site spigot
https://pastebin.com/Libt04yg

**Comment by Nort721** [comment]
does the error happen when you try using the NCP check?

**Comment by DaffyDG** [comment]
no when player join born this error i dont known why i use recomended protocolib (sorry bad english)

**Comment by Nort721** [comment]
Have you tried updating to Build 30 BETA?

**Comment by DaffyDG** [comment]
yes no i'm DG_Daffy now dont have any problem working so good <3
