### ISSUE TITLE
Only errors, AC is not banning only kicking...

### ISSUE THREAD

**Issue by Aimtt123** [Nort721/GodsEye-Issues#13]
Version: 1.8.8
ProtocolLIB version: 4.4.0, i tested all...
Logs: https://hastebin.com/axohefetef.md

Only errors ..... pls fix it......

**Comment by Nort721** [comment]
Hey, please try updating to the latest version from spigot and see if the same error still happens

**Comment by Nort721** [comment]
issue solved
