### ISSUE TITLE
GodsEye Plugin

### ISSUE THREAD

**Issue by FaridJaffa** [Nort721/GodsEye-Issues#131]
Hello i am using just only your anticheat plugin godseye but my players can use flywalk even though they do not have fly permission how can we solve it?

**Comment by Nort721** [comment]
It does not make much sense, this may be one of your plugins blocking GodsEye in some way, you should try using AirWalk on the server, if you manage to bypass try removing plugins and try it again until your detected then you can know what plugin makes the issue happen, also you should try it on our test server

**Comment by Nort721** [comment]
Please contact me on a spigot DM if the issue still happens, we can try to investigate more then if it still happens
My discord: Nort721#0001
