### ISSUE TITLE
False Detections.  Ping spoof & Inventory actions

### ISSUE THREAD

**Issue by ItzMystic** [Nort721/GodsEye-Issues#133]
**_False detections   ( Ping spoof & Inventory actions_** 

1) GodsEye version - **Inventory actions  & Ping spoof happend on version 29.  And ping spoof still happend on version 27** 
2) Server Version+Fork- **1.8.8**
3) ProtocolLib version - **Downloaded the version godseye told me to download**
4) server log - **Not needed ( no info about the issue )**
5) We recommend sending a video/screenshot of the issue if possible, so we would be able to fix it faster. - **No screenshot needed**
6) A very detailed description of the issue - **Inventory actions: I keep getting some false detections about inventory actions. this can happend rly anywhere.  Ping spoof: I get ping spoof detections from one player and one player only. This player is using a** _Chat app_ **that u can get on phone to chat with people on java versions servers. I have no idea why this happends but it would be awesome if  u guys had a fix**

**Comment by Nort721** [comment]
Did some tweaks for both of these checks, hopefully, will help to make them more stable
