### ISSUE TITLE
Stacktrace with IllegalStateException "Start block messed in BlockIterator"

### ISSUE THREAD

**Issue by haloflooder** [Nort721/GodsEye-Issues#134]
A bug report/issue report should contain:

1) GodsEye Build 29 Beta
2) git-Paper-1618 1.12.2
3) 4.4.0
4) https://pastebin.com/hx6rU1as
5) N/A
6) Console gets spammed with this stracktrace until reboot. Not sure what exactly caused it since it happened while testing a minigame server with a few people. Most of the players were using 1.8 clients. Will try to replicate it with more testing later.

**Comment by Nort721** [comment]
That's very wired since it happens in a line that I just use a normal bukkit API method, so that means that there is an error in the spigot API? even though I doubt it, I will investigate more into this

How many times did it happen to you?

**Comment by haloflooder** [comment]
This pretty much is happening everytime the server is being used. I'm pretty sure it might be coming from a specific hack check but I'm not sure what hack check it would be coming from.

**Comment by Nort721** [comment]
Outdated issue, please reopen it with a log of the same error from the latest version if it still happens
