### ISSUE TITLE
Godseye not enabled. Can someone manually enable it for me?

### ISSUE THREAD

**Issue by ScrubMT** [Nort721/GodsEye-Issues#135]
A bug report/issue report should contain:

1) GodsEye version Latest as of 4/2/2020
2) Server Version+Fork Spigot 1.14.4
3) ProtocolLib version 
Latest as of 4/2/2020

4) Server log (02.04 23:23:14 [Server] Server thread/INFO Enabling GodsEye vBuild 29 BETA
02.04 23:23:15 [Server] Server thread/INFO activation failed!
02.04 23:23:15 [Server] Server thread/INFO Your GodsEye copy is not activated for an unknown reason, please contact TopRaider or Nort721 for manual activation
02.04 23:23:15 [Server] Server thread/INFO Disabling GodsEye vBuild 29 BETA
02.04 23:23:15 [Server] Server thread/INFO has been disabled)
5) We recommend sending a video/screenshot of the issue if possible, so we would be able to fix it faster.
6) A very detailed description of the issue
![firefox_UQj4Tg0J1X](https://user-images.githubusercontent.com/63079658/78309936-aa449c00-7509-11ea-9662-47502a812e32.png)

**Comment by Nort721** [comment]
your copy has been enabled
