### ISSUE TITLE
Timer A false flagging

### ISSUE THREAD

**Issue by MateoNikolic** [Nort721/GodsEye-Issues#137]
A bug report/issue report should contain:

1) Build 29 Beta
2) 1.12.2 PaperSpigot fork called kSpigot
3) 4.4.0-b421
5) https://i.imgur.com/2RL72QS.png
6) when using teleport between worlds

**Comment by Nort721** [comment]
Will make sure to check that out, thanks for the report!

**Comment by Nort721** [comment]
Should be fixed now
