### ISSUE TITLE
Jesus Check

### ISSUE THREAD

**Issue by ToxicGR** [Nort721/GodsEye-Issues#138]
A bug report/issue report should contain:

1) GodsEye version: Latest
2) Server Version+Fork: 1.8.8
3) ProtocolLib version: Latest
4) Server log: doesn't need to
5) We recommend sending a video/screenshot of the issue if possible, so we would be able to fix it faster.: https://www.youtube.com/watch?v=T6NlZSeRmVA
6) A very detailed description of the issue
I know that the Jesus check is at a every earlty stage but it doesn't do anything at all even if you have it enabled or disabled is the same thing. No violations messages at all.

**Comment by Nort721** [comment]
Latest ProtocolLib is not the correct one for 1.8.X, please download the correct one from GodsEye's spigot overview

**Comment by Nort721** [comment]
Releasing an experimental recoded new Jesus check if it would go good trough further testing
