### ISSUE TITLE
Copy Unactivated

### ISSUE THREAD

**Issue by Smitezy** [Nort721/GodsEye-Issues#140]
A bug report/issue report should contain:

1) BETA 29 Build
2) 1.8 Paperspigot
3) 4.5
4) 20:32:11 INFO]: [GodsEye] Enabling GodsEye vBuild 29 BETA
> [20:32:12 INFO]: [GodsEye] activation failed!
> [20:32:12 INFO]: [GodsEye] Your GodsEye copy is not activated for an unknown reason, please contact TopRaider or Nort721 for manual activation
> [20:32:12 INFO]: [GodsEye] Disabling GodsEye vBuild 29 BETA
> [20:32:12 INFO]: [GodsEye] has been disabled
6) Whenever I boot my server, it says my copy is unactivated, and to contact you guys, even though I just bought it from SpigotMC.

**Comment by Nort721** [comment]
Hey there, your copy should work now, sorry for the wait please confirm to me if it works or not so I can close this issue

**Comment by Smitezy** [comment]
It works! Thanks!
