### ISSUE TITLE
The KillAura I check is really easy to false flag

### ISSUE THREAD

**Issue by ThePineapple27** [Nort721/GodsEye-Issues#141]
1) GodsEye version **Build 29 Beta**
2) Server Version+Fork **Paperspigot 1.8**
3) ProtocolLib version **4.5.0**
4) Server log 

**0f744bc8-0015-4a61-bdd4-bd02463a9689:**
  **LogsCount: 1**
  **'1':**
    **Date: 25-026-2020**
    **Detection: KILLAURA**
    **Type: TypeI**
    **TPS: 20.0**
    **Ping: 47**
    **PunishType: KICK**

**Nothing unusual in latest.log**

5) We recommend sending a video/screenshot of the issue if possible, so we would be able to fix it faster.
**The video below is shown with verbose mode on**
https://youtu.be/JikD0AfI0Ik
6) A very detailed description of the issue
**A player is able to click both of their mouse buttons at any CPS in a seemingly random fashion with a bow in hand (with arrows) in order to falsely trigger the KillAura I check. I saw a similar issue stating this is also possible with blockhitting.**

**Comment by Nort721** [comment]
Hey there, please use the correct version of ProtocolLib, download the correct one from GodsEye's spigot overview

**Comment by Nort721** [comment]
Should be fixed now
