### ISSUE TITLE
You can false flag Reach B with thorns and AFK 101 training

### ISSUE THREAD

**Issue by ThePineapple27** [Nort721/GodsEye-Issues#142]
1) GodsEye version **Build 29 Beta**
2) Server Version+Fork **Paperspigot 1.8**
3) ProtocolLib version **4.5.0**
4) Server log

    **Date: 25-022-2020**
    **Detection: REACH**
    **Type: TypeB**
    **TPS: 20.0**
    **Ping: 58**
    **PunishType: KICK**

**Nothing notable in latest.log**

5) We recommend sending a video/screenshot of the issue if possible, so we would be able to fix it faster.
**Verbose mode is enabled.**
https://youtu.be/Fmm6NghP2Sw

6) A very detailed description of the issue
**A player is able to incorrectly flag the Reach Type B check by wearing armor with thorns and being shot at from a long distance.**

**Comment by Nort721** [comment]
Fixed for next version
