### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by jackstaak** [Nort721/GodsEye-Issues#143]
A bug report/issue report should contain:

1) GodsEye version: build 29 BETA
2) Server Version+Fork: 1.8.8 spigot 
3) ProtocolLib version: 4.4.0
4) Server log: https://pastebin.com/nxmxhVGG
5) We recommend sending a video/screenshot of the issue if possible, so we would be able to fix it faster: https://prnt.sc/s89rfh
6) A very detailed description of the issue: It just gived this error...

**Comment by Nort721** [comment]
The error you sent is most likely not complete, please send the full error

**Comment by Nort721** [comment]
Outdated issue caused of inactivity, please reopen the issue with an error log from the latest version if it still happens in the latest version
