### ISSUE TITLE
Error Log

### ISSUE THREAD

**Issue by Darklom** [Nort721/GodsEye-Issues#145]
A bug report/issue report should contain:

1) GodsEye version
29B

2) Server Version+Fork
PaperSpigot #273 - 1.15.2

3) ProtocolLib version
ProtocolLib v4.5.0
4) Server log
https://pastebin.com/CueNQ8JX

5) We recommend sending a video/screenshot of the issue if possible, so we would be able to fix it faster.
N/A

6) A very detailed description of the issue
https://pastebin.com/YCF8HxwV

**Comment by Nort721** [comment]
Should be fixed now
