### ISSUE TITLE
[Suggestion] Anti-nuker

### ISSUE THREAD

**Issue by Darklom** [Nort721/GodsEye-Issues#146]
PaperSpigot 1.15.2 - Suggestion - Anti-Nuker

A player can login with https://aristois.net/ (free version) and crash the server sending what appear to be "bad packets".  However, sometimes the gods' eye catches this and kicks them from the server.

It is detected as "BadPackets" - TypeH

https://media.discordapp.net/attachments/708967446572433488/709010473743548426/unknown.png?width=880&height=476

Suggestion is to add an anti-nuker

**Comment by Nort721** [comment]
Check added, will be most likely released next update if it goes trough further testing, if not I will reopen the issue
