### ISSUE TITLE
Seperate Error Log

### ISSUE THREAD

**Issue by Darklom** [Nort721/GodsEye-Issues#147]
A bug report/issue report should contain:

GodsEye version
29B

Server Version+Fork
PaperSpigot #273 - 1.15.2

ProtocolLib version
ProtocolLib v4.5.0

Server log
https://pastebin.com/CueNQ8JX

We recommend sending a video/screenshot of the issue if possible, so we would be able to fix it faster.
N/A

6) A very detailed description of the issue
https://pastebin.com/viWEkaYc

**Comment by Nort721** [comment]
Seems like a wired error, any chance you can replicate it and send here another stacktrace?

**Comment by Nort721** [comment]
Check if the error happens in latest version, make sure to comment here if not, if yes then post the new stacktrace

**Comment by Nort721** [comment]
Hey there, please let me know if it still happens to you in the latest build, 34 BETA, of there is no response in 7 days this issue will be closed for outdated and inactivity tags, sorry for taking so long to answer Im just very busy IRL

**Comment by Nort721** [comment]
outdated issue, if the error still happens please post a new error log for the latest build and reopen the issue
