### ISSUE TITLE
TPS Drop (Performance - 1.15.2)

### ISSUE THREAD

**Issue by Darklom** [Nort721/GodsEye-Issues#148]
A bug report/issue report should contain:

GodsEye version
29B

Server Version+Fork
PaperSpigot #273 - 1.15.2

ProtocolLib version
ProtocolLib v4.5.0

Server log
https://pastebin.com/CueNQ8JX

We recommend sending a video/screenshot of the issue if possible, so we would be able to fix it faster.
N/A

A very detailed description of the issue
At about 6 players, it started taking a massive performance dip and destroyed server TPS

https://media.discordapp.net/attachments/708967446572433488/709031135648284773/unknown.png?width=1080&height=41

https://media.discordapp.net/attachments/708967446572433488/709031293647716352/unknown.png?width=1080&height=199

**Comment by Darklom** [comment]
https://timings.aikar.co/?id=0723100b78614ad5885b42becc003c15

**Comment by Nort721** [comment]
The flying packet thing is actually not impacted much by GodsEye, flying packets are used in all kinds of stuff of the servers code, seems like some movement checks cause some bigger performance impact, I'll make sure to work on more optimizations for them also in next versions I'm adding a new feature that will allow making some of the movement checks run on separated thread and by that give almost no performance impact on the main thread, therefore, lower TPS impact

**Comment by Nort721** [comment]
I'll be bringing more and more performance improvement all the time, therefore, I'm closing this issue, will be happy to get more and more timings from you if you have ones in new info (you can send them in discord premium-support channel in the discord server), you can also ask to reopen this issue if you need me to for whatever reason

**Comment by Darklom** [comment]
@Nort721 

Much improved performance!  It is playable now on 1.15.2.  Great job Nort.  I am currently using 30B with the optional feature enabled.  However, there is still a bit of high performance usage that could potentially be improved.    Attached are my timings - https://timings.aikar.co/?id=12ca8e59d0c94a61a58a8a819c833b59

Notable performance hits - 
GodsEye::Event: g.aa (PlayerMoveEvent)count(2219)  total(35.99% 18.164s, 49.56% of tick)avg(8.19ms per - 24.78ms/3.03 per tick)
GodsEye::Event: g.aa (PlayerMoveEvent) (SELF)count(2219)  total(35.98% 18.16s, 49.55% of tick)avg(8.18ms per - 24.78ms/3.03 per tick)
