### ISSUE TITLE
Error with PlayerMoveEvent (might be error with ban system)

### ISSUE THREAD

**Issue by jackstaak** [Nort721/GodsEye-Issues#149]
A bug report/issue report should contain:

1) 29 BETA 
2) 1.8.8 spigot 
3) 4.4.0
4) https://pastebin.com/
5) https://pastebin.com/
6) Well after a couple times that I got kicked for speed probably around 2 times it should be banning me since I set in made that in the config.. After 2 kicks a ban, but it just gives this error idk if it has to do anything with the not working ban system but I wanted to make this issue anyway since yeah.

**EDIT**
I have also tried the ban system with a different check: Killaura. It has exactly the same problem after 2 kicks so when you should get banned it is giving the same error and it is not kicking/banning at all. The checks just start over again like nothing happend.

**Comment by Nort721** [comment]
You didn't link a pastebin with a past in it
