### ISSUE TITLE
2 false positives

### ISSUE THREAD

**Issue by SladeHazard** [Nort721/GodsEye-Issues#150]
When bow boosting with a punch II bow it falses SPEED type e and when you hit someone with a axxe it falses noswing type a server version 1.12.2

**Comment by Nort721** [comment]
The NoSwing false probably happens if you run ViaBackWards or ProtocolSupport which causes to NoSwing false and it can't be fixed in my end

**Comment by Nort721** [comment]
Ok I did a fix where NoSwing will not check players that their client version is lower than the server base version so it will prevent NoSwing false positives in such case, for the speed I did some tweaks to it, seems to do the trick
