### ISSUE TITLE
Console Error Log (Vanilla Fly)

### ISSUE THREAD

**Issue by Darklom** [Nort721/GodsEye-Issues#151]
A bug report/issue report should contain:

GodsEye version
30B

Server Version+Fork
PaperSpigot #273 - 1.15.2

ProtocolLib version
ProtocolLib v4.5.0

Server log
https://pastebin.com/CueNQ8JX

We recommend sending a video/screenshot of the issue if possible, so we would be able to fix it faster.
N/A

A very detailed description of the issue

(Vanilla Fly Cheating)

https://pastebin.com/s4wKjLtn

**Comment by Nort721** [comment]
Should be fixed for next version, if you still get any issues with it please let me know on discord and I will reopen the issue
