### ISSUE TITLE
1.15.2 Error Log (5 seperate Console errors)

### ISSUE THREAD

**Issue by Darklom** [Nort721/GodsEye-Issues#152]
A bug report/issue report should contain:

(POSTED FIVE ERRORS TOGETHER SO AS NOT TO SPAM YOUR GITHUB)

GodsEye version
30B

Server Version+Fork
PaperSpigot #273 - 1.15.2

ProtocolLib version
ProtocolLib v4.5.0

Server log
https://pastebin.com/CueNQ8JX

We recommend sending a video/screenshot of the issue if possible, so we would be able to fix it faster.
N/A

A very detailed description of the issue

NUMBER - 1
https://pastebin.com/jk1YTsPB

NUMBER - 2

https://pastebin.com/TyYMMkD8

NUMBER - 3

https://pastebin.com/G4nL9A4h

NUMBER - 4

https://pastebin.com/MWjMZKDy

NUMBER - 5   (when Jesus walk?)
https://pastebin.com/6wEbcJXm

**Comment by Darklom** [comment]
6th - 

https://pastebin.com/LnjBaZs5

**Comment by Nort721** [comment]
1 and 5 are the same error
2 is not an error
3 and 4 are the same error

so there are 3 errors actually here

**Comment by Nort721** [comment]
Should be fixed in next version, if one of these still happens let me know on discord and I'll reopen this issue
