### ISSUE TITLE
ONpacketreceiving error on teleport 

### ISSUE THREAD

**Issue by jackstaak** [Nort721/GodsEye-Issues#153]
A bug report/issue report should contain:

1) 30B
2) Spigot 1.8.8
3) 4.5.0
4) https://pastebin.com/paNkjhzu
5) https://pastebin.com/paNkjhzu
6) On forced teleport (gets switched between different worlds)

**Comment by Nort721** [comment]
Should be fixed for next version, if it still happens then tell me on discord and I'll reopen this issue
