### ISSUE TITLE
False Positives with Fly TypeA and TypeC

### ISSUE THREAD

**Issue by Darklom** [Nort721/GodsEye-Issues#154]
A bug report/issue report should contain:

GodsEye version
30B

Server Version+Fork
PaperSpigot #273 - 1.15.2

ProtocolLib version
ProtocolLib v4.5.0

Server log
https://pastebin.com/CueNQ8JX

We recommend sending a video/screenshot of the issue if possible, so we would be able to fix it faster.
N/A

A very detailed description of the issue

Fly TypeC is triggered when a player jumps on a bed and causes damaged as it teleports them back
Fly TypeA is triggered when flying with an Elytra (and using rocket)

**Comment by Nort721** [comment]
Should be fixed next update, if the issue still happens let me know on discord and I will reopen the issue
