### ISSUE TITLE
False flags on Autoclicker type G and autoclicker type B+D while butterfly clicking (butterfly clicking is enabled in checks.yml)

### ISSUE THREAD

**Issue by jackstaak** [Nort721/GodsEye-Issues#155]
A bugs report/issue report should contain:

1) 30B 
2) spigot 1.8.8
3) 4.5.0
4) Don't need that 
5) https://prnt.sc/sh5arl Autoclicker type G is a known issue so I don't have a ss of that.
6) So when just jitterclicking you can easy false flag autoclicker type G, when butterfly clicking between the 20 and 30 cps it gets easily false flagged. Dejavu did a paladin check on the guy that got like between 20 and 30 cps and he is not hacking

**Comment by Nort721** [comment]
Fixed what was reported here, I do not recommend to allow butterfly clicking on your server since it will make AutoClicker detection weaker
