### ISSUE TITLE
Speed type F on test server 

### ISSUE THREAD

**Issue by jackstaak** [Nort721/GodsEye-Issues#156]
A bugs report/issue report should contain:

1) Test server 
2) Test server 
3) Test server 
4) https://prnt.sc/sh5fqp
5) https://prnt.sc/sh5fqp 
6) So I was just walking around on the test server and it was flagging me for speed, I have nothing enabled on my hack client..

**Comment by Nort721** [comment]
Speed TypeF therefore still in development and has not been released
