### ISSUE TITLE
False flag Reach type B 

### ISSUE THREAD

**Issue by jackstaak** [Nort721/GodsEye-Issues#157]
A bug report/issue report should contain:

1) 30B
2) spigot 1.8.8 
3) 4.5.0
4) https://prnt.sc/sh5l1x + https://prnt.sc/sh5l8f
5) https://prnt.sc/sh5l8f + https://prnt.sc/sh5l1x
6) So the "Greenlio" person has 130 ping but the Cxssi person has like between 1 and 20.. and it is false flagging type B

**Comment by Nort721** [comment]
issue outdated, should be fixed on latest
