### ISSUE TITLE
false flagging Killaura type: H and sometimes type A 

### ISSUE THREAD

**Issue by jackstaak** [Nort721/GodsEye-Issues#158]
A bug report/issue report should contain:

1) 30B
2) spigot 1.8.8
3) 4.5.0
4) https://prnt.sc/sh6qza + https://prnt.sc/sh6pk5 + https://prnt.sc/sh6km4
5) https://prnt.sc/sh6qza + https://prnt.sc/sh6pk5 + https://prnt.sc/sh6km4
6) So when you just pvp it is all ok but after pvp'ing for a while it is just false flagging a lot and dangerous since I have bans enabled after like 4 kicks..

**Comment by Nort721** [comment]
Did you manage to make this happen in the test server?

**Comment by jackstaak** [comment]
No I didn't yet I don't want to drag my players to the test server or test a hour long... I do know that it is happening on my server, and I don't think that any other plugin is f*cking with godseye.

**Comment by Nort721** [comment]
You don't need to grad your players to the test server but maybe learn how to replicate the issue yourself, are you sure the players were not hacking? this issue has never happened to me and I simply can't fix the issue if I can't replicate it, it also never happened to my testers, also I have never got reports from someone saying this happens to him, TypeH is a very old check is I may recode it at some point

**Comment by jackstaak** [comment]
Well I don't really want to try it since it doesn't really happen very often but it does happen, and that would mean that I need to invest a lot of time in testing it since it happens after pvp'ing for a while.. Maybe you could just take a look at the code and see what you can do? Idk about the testers but what I do know is is that it happens after a while of intense pvp'ing so maybe your testers didn't pvp't that much intens?

**Comment by Nort721** [comment]
We did test it a lot, and never hade these issues so sorry I can't really replicate it to fix it, I took a lot at the code and didn't see anything wrong as said this check will be replicated in a few updates, for now, disable it or find how to replicate the issue

**Comment by Nort721** [comment]
Issue closed for lack for info, checks that are possible to be recoded will be recoded to try solving the issue if you manage to make the issue happen on the test server let me know
