### ISSUE TITLE
False flagging Hitobox type: A 

### ISSUE THREAD

**Issue by jackstaak** [Nort721/GodsEye-Issues#159]
A bug report/issue report should contain:

1) 30B
2) spigot 1.8.8
3) 4.5.0
4) https://prnt.sc/sh6pc3 + https://prnt.sc/sh6l48
5) https://prnt.sc/sh6pc3 + https://prnt.sc/sh6l48
6) This just happens randomly while pvp'ing.. Sometimes while critting but I can't see a special reason begind these false flags...

**Comment by Nort721** [comment]
it may throw sometimes but this would most likely not lead to a ban, you can disable the check if you are really scared or increase max violations, the flags are not very often so they will probably get deleted after some time
