### ISSUE TITLE
Bug 1.14.4

### ISSUE THREAD

**Issue by SladeHazard** [Nort721/GodsEye-Issues#16]
A bug report/issue report should contain:

1) Paper 1.14.4
2) 4.5.0-SNAPSHOT
3) https://pastebin.com/veWaRtE4 SKIP TO THE END
4) i don't think this needs a video
5) Simple just purchased godseye and i did /godseye profile [player] then did a bot test and the error spammed and no bots spawned or anything happend

**Comment by Nort721** [comment]
This is a pretty complicated issue with the bot check, will do our best to fix it fast as we can

**Comment by Nort721** [comment]
Will be solved when the recode will be out, thanks for the report
