### ISSUE TITLE
False flag reach type A (not a lot)

### ISSUE THREAD

**Issue by jackstaak** [Nort721/GodsEye-Issues#161]
A bug report/issue report should contain:

1) 30B 
2) spigot 1.8.8
3) 4.4.0
4) https://prnt.sc/shej9t
5) https://prnt.sc/shej9t + https://prnt.sc/shejxg + https://prnt.sc/shek8u
6) So he could possibly had a hard laggspike cuz his internet is not stable.. He probably had a lagspike to like 300 - 400 ping. We where just pvp'ing and this randomly happend while he was lagging. Reach type A normally isn't flase flagging a lot but randomly sometimes...

**Comment by Nort721** [comment]
Got it, should be a pretty easy fix

**Comment by Nort721** [comment]
Improved lag resistance for TypeA for next update, thanks for the report
