### ISSUE TITLE
False flagging aim assist type B 

### ISSUE THREAD

**Issue by jackstaak** [Nort721/GodsEye-Issues#162]
A bug report/issue report should contain:

1) 31B 
2) spigot 1.8.8
3) 4.4.0
4) https://prnt.sc/shj4w8
5) https://prnt.sc/shj4w8
6) So this got false flagged, stable tps might had a small lagspike not sure. Just on pvp'ing or/and pressing on a npc.  This dude is definetely not cheating he is really bad at pvp so yh.

**Comment by Nort721** [comment]
I see, Disable AimAssist TypeH until next update

**Comment by Nort721** [comment]
Check seems to be fine after the changes in Build 35 BETA, please open a new issue with latest version if it still happens
