### ISSUE TITLE
BanWave

### ISSUE THREAD

**Issue by SladeHazard** [Nort721/GodsEye-Issues#163]
banwaves do nothing for 1.12.2 paper please fix asap...... i dont like kicking users even if i go on flux and hack blatantly and get detected it doesnt kick or adds me in banwave yes banwaves are enabled in config and i'm using effect 1

**Comment by SladeHazard** [comment]
kicks don't work either bruh im running flamecord bungee fyi and using: https://www.spigotmc.org/resources/godseyesync-mysql-and-bungeecord-synchronization.78815/ if i dont use that it kicks operators to hub when a hacker gets kicked.

**Comment by Nort721** [comment]
This is a GodsEyeSync bug, kicking and banning normally works on GodsEye, I'm not the developer of GodsEyeSync and does not have anything to do with it, you should probably contact GodsEyeSync's developer on spigot and report about the bug
