### ISSUE TITLE
Autoclicker type H false flagging a lot 

### ISSUE THREAD

**Issue by jackstaak** [Nort721/GodsEye-Issues#164]
A bug report/issue report should contain:

1) 31B
2) spigot 1.8.8
3) 4.4.0
4) https://prnt.sc/shuyy0
5) https://prnt.sc/shuyy0 + https://prnt.sc/shuz3z + https://prnt.sc/shuz79
6) He is normal clicking not butterfly or jitterclick it randomly happend while pvp'ing..  7-8 cps

**Comment by Nort721** [comment]
I see disable TypeH for now

**Comment by Nort721** [comment]
Recoded AutoClicker TypeH for next version
