### ISSUE TITLE
Consolespamming PacketPlayInUseEntity

### ISSUE THREAD

**Issue by dorsax** [Nort721/GodsEye-Issues#165]
A bug report/issue report should contain:

1) GodsEye version: Build 30 Beta, Full Premium
2) Server Version+Fork paper-spigot: Paper version git-Paper-161 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)
3) ProtocolLib version: v4.5.0
4) Server log https://pastebin.com/ePaeDWjh
5) We recommend sending a video/screenshot of the issue if possible, so we would be able to fix it faster. N/A
6) A very detailed description of the issue

It spams the console hard, we cannot really use the outputs!

**Comment by Nort721** [comment]
Has been fixed in Build 31 and 32
