### ISSUE TITLE
False flag killaura type D

### ISSUE THREAD

**Issue by jackstaak** [Nort721/GodsEye-Issues#166]
A bug report/issue report should contain:

1) 31B
2) mSpigot 1.8.8
3) 4.4.0
4) https://prnt.sc/shxj5h
5) https://prnt.sc/shxj5h + https://prnt.sc/shxkcc + https://prnt.sc/shxki0
6) Just pvp'ing and this happens, normal clicking, not lagging, good tps, steady ping.

**Comment by Nort721** [comment]
Disable Killaura TypeD for now until next update

**Comment by Nort721** [comment]
Did some tweaks to Killaura TypeD, most likely hopefully, will fix this
