### ISSUE TITLE
Godseye error (Big error) 

### ISSUE THREAD

**Issue by jackstaak** [Nort721/GodsEye-Issues#167]
A bug report/issue report should contain:

1) 31B
2) mSpigot 1.8.8
3) 4.4.0
4) https://pastebin.com/gH97nmNP
5) https://pastebin.com/gH97nmNP
6) So right before that I did /spawn and I got switched between worlds, idk if it has anything to do with it but that is what happend. Nothing else happend I was just online on my server with noone else.

**Comment by Nort721** [comment]
Did you hade async movement enabled?

**Comment by Nort721** [comment]
Also try updating to latest Build as see if it still happens

**Comment by jackstaak** [comment]
I disabled async movement, and yeah I will try it later today

**Comment by jackstaak** [comment]
I tried it with the newest version and it is giving the same error....

**Comment by Nort721** [comment]
Are you sure you got this error while using Build 31 BETA?

**Comment by jackstaak** [comment]
Yes and beta 32

**Comment by Nort721** [comment]
Yeah but in which version was the pastebin error produced

**Comment by jackstaak** [comment]
31 but i have the same error in 32

**Comment by Nort721** [comment]
Most likely fixed in latest
