### ISSUE TITLE
False positives elicited in multiple different ways

### ISSUE THREAD

**Issue by funkemunky** [Nort721/GodsEye-Issues#168]
A bug report/issue report should contain:

1) Test Server
2) Test Server
3) Test Server
4) Test Server
5) https://www.youtube.com/watch?v=YVR8MEvQ8XA
6) Watch the video.

**Comment by Nort721** [comment]
Honestly, I'm really not sure how all of that is happening, I'm also not sure all of that has gone through testing and most of it has never happen to most of my users or while the plugin was servers that have around 150 - 200 players, but I'm surely going to look into it and see how it happened so thank you for opening my eyes to that and helping me catch this while the plugin is still in BETA stages

**Comment by Nort721** [comment]
seems like that the AutoClicker checks got broken due to the new system that I use to detect if the player is breaking a block or not so once I'll fix that system all of the checks will go back to working properly

**Comment by funkemunky** [comment]
Honestly just use the PlayerInteractEvent for checking if a player is
breaking blocks. Normally you have to raytrace yourself but if your
autoclicker checks don’t flag within one or two ticks it should be fine.
This is what I use since it saves a bit on performance. Also, your reach
check is falsing like that because you’re calculating my distance from the
center of the player, not from the outside of their box. Where I hit should
be quite more than .3 blocks from the center.

**Comment by funkemunky** [comment]
For your Aim H check, patching that isn’t going to be very simple. You’re
going to have to implement the cinematic smoothing algorithm that Minecraft
uses. If you have any questions on how to do this, just add me on Discord.

**Comment by Nort721** [comment]
Hmm I see that now, I actually didn't use PlayerInteractEvent when changing systems last update because I was pretty sure that the PlayerInteractEvent is called using Dig packets so I just went to use dig packets right away, for calculating HitBox I've tried to start working on this with Reach Type Honestly, I may apply it to TypeA next update

**Comment by funkemunky** [comment]
No, the PlayerInteractEvent raytraces to see if you’re interesting with a
block. Check MovingObjectPosition inside the AxisAlignedBB class. This is
what Minecraft uses on the client side to find what you’re looking at.

**Comment by Nort721** [comment]
Thank you for the offer, I indeed also started researching of how to detect if the player is using optifine zoom and tried some stuff, it seems to be indeed pretty complicated

**Comment by Nort721** [comment]
Issues solved, the fixes will be tested more and released in the next update, thanks for the report and suggestions
