### ISSUE TITLE
Time type A false flag

### ISSUE THREAD

**Issue by jackstaak** [Nort721/GodsEye-Issues#169]
A bug report/issue report should contain:

1)31B
2) 1.8.8 mSpigot
3) 4.4.0
4) https://prnt.sc/siad
5)  https://prnt.sc/siad + https://prnt.sc/siadjk + https://prnt.sc/siadqk
6) Sp sometimes when a player joins it gets false flagged with timer Type A

**Comment by Nort721** [comment]
Has been recoded since this was made
