### ISSUE TITLE
Spider/WallClimb

### ISSUE THREAD

**Issue by RealWentox** [Nort721/GodsEye-Issues#17]
A bug report/issue report should contain:

1) The official Testserver
2) The official Testserver
3) I think its dont needed (Time of testing: Timezone MESZ: 8:20 p.m)
4) https://streamable.com/8g3ta
5) Spider/WallClimb works on GodsEye Version: Build 13

**Comment by SladeHazard** [comment]
this does get detecteD?

**Comment by Nort721** [comment]
it's a bypass, working on a new check for it, hopefully, will be released in the next few versions after the recode

**Comment by ventOwO** [comment]
maybe you should improve your fly check instead of making a new one

**Comment by Nort721** [comment]
well I am planning on improving the move check to fix this bypass

**Comment by Nort721** [comment]
Issue will be patched when the new fly check will be out
