### ISSUE TITLE
Reach A + B and Autoclicker G

### ISSUE THREAD

**Issue by funkemunky** [Nort721/GodsEye-Issues#170]
1) Test Server
2) Test Server
3) Test Server
4) Test Server
5) https://youtu.be/4NLvk-FmTKw
6) It appears that Reach A was slightly fixed. I finally figured out how to recreate the Reach B false positive. It doesn't appear to be caused by the same issue as Reach A, however. Autoclicker G occasionally false flagged but it might not be an issue. I butterfly clicked on my Razer Deathadder Elite from 2018. I have never experienced double clicking with my mouse so that is not the problem.

**Comment by Nort721** [comment]
The Reach TypeA fix has not been uploaded yet to the test server, for butterfly clicking there is an option in the checks.yml that needs to be enabled to allow butterfly clicking even though it may have not been fully migrated with the new AutoClicker checks though

**Comment by Nort721** [comment]
Also Seems like I can't replicate the Reach TypeB false positive

**Comment by Nort721** [comment]
Has been already fixed in 34 BETA, fully fixed in next version
