### ISSUE TITLE
vclip bypass

### ISSUE THREAD

**Issue by llaurenss** [Nort721/GodsEye-Issues#173]
A bug report/issue report should contain:

1 - 4) test server
5) https://www.youtube.com/watch?v=YsT78ubjqbA
6) vclip bypasses

**Comment by Nort721** [comment]
I'm pretty sure that this is not VClip, looks more like step named VClip but I will check this out

**Comment by llaurenss** [comment]
This video shows it better: https://youtu.be/HlrqmJI87YA

**Comment by Nort721** [comment]
Detected by the new recoded Move TypeH
