### ISSUE TITLE
hight jump & fly bypass

### ISSUE THREAD

**Issue by DaffyDG** [Nort721/GodsEye-Issues#177]
A bug report/issue report should contain:

1) test server
2)  test server
3)  test server
4)  test server
5) https://www.youtube.com/watch?v=YzHYHfgEKEI
6) hight jump & fly bypass When I stand Slime Block

**Comment by Nort721** [comment]
That, unfortunately, cannot be fixed without risking false positives happening and with GodsEye we prefer stability over checks strength in most cases we make sure to achieve both but in that case, we prefer to go for stability
