### ISSUE TITLE
Additions

### ISSUE THREAD

**Issue by CocoCC3** [Nort721/GodsEye-Issues#181]
I want to added antiautoarmor fastbreak fastplace and antixrayde additions.

**Comment by Nort721** [comment]
AntiXray - won't be added, also paper has a pretty good AntiXray system and its free

AntiAutoArmor - sounds pretty interesting, may be added in the future

FastPlace - The scaffold check may also detect some fastplace hacks, but here is currently no official check against it, will maybe consider adding one in the future
