### ISSUE TITLE
speed type A false positive

### ISSUE THREAD

**Issue by llaurenss** [Nort721/GodsEye-Issues#183]
A bug report/issue report should contain:

1) Build 33 beta
2) paperspigot 1.8.8
3) protocollib version: 4.4.0
5) https://youtu.be/szOq1K9Qd1U
6) Make a slime block push you across the ground

**Comment by Nort721** [comment]
Can't replicate the issue for some reason, doesn't happen to me ¯\_(ツ)_/¯
