### ISSUE TITLE
movement type B false positive

### ISSUE THREAD

**Issue by llaurenss** [Nort721/GodsEye-Issues#184]
A bug report/issue report should contain:

1) Build 33 beta
2) paperspigot 1.8.8
3) protocollib version: 4.4.0
5) https://youtu.be/QgJwJ7naz68
6) Walk across ice and soul sand

**Comment by Nort721** [comment]
Can't see how in normal gameplay this would happen but sure seems like an easy fix

**Comment by Nort721** [comment]
has been fixed in latest version
