### ISSUE TITLE
not so much of an issue but a request

### ISSUE THREAD

**Issue by Tubby2020** [Nort721/GodsEye-Issues#185]
can you add it so instead of kicking it if you want you can make it ban players also as i wan't to ban cheaters not kick then thanks for your time.

**Comment by Nort721** [comment]
Hey there, you can make the plugin ban without kicking by opening the checks.yml file and disable the "Kick player" setting to "Disabled", also if banning is not working for you its most likely an issue with your banning command (maybe it can't run from console?) also if you are running GodsEyeSyn you should contact its developer about this issue (you can contact him with a spigot conversation)
