### ISSUE TITLE
Request more log information...

### ISSUE THREAD

**Issue by jackstaak** [Nort721/GodsEye-Issues#186]
A bug report/issue report should contain:

Just when you do /logs playername you get some more information about what how many blocks reach how many cps etc. Like as much information possible to make it easier to see if that guy was cheating hard of like 3.1 reach etc. Maybe you could find something for movement 2? Like if it was bhopping or stuff like that...

**Comment by Nort721** [comment]
Sounds like a good idea, will surely work on it for future updates
