### ISSUE TITLE
Killaura

### ISSUE THREAD

**Issue by CocoCC3** [Nort721/GodsEye-Issues#189]
A bug report/issue report should contain:

1) GodsEye version 1.8
2) Spigot
3) 1.8
4) Server log
5) https://www.youtube.com/watch?v=vUt19Ciwd3o&feature=youtu.be
6) Fly dosent give a big problem but killaura is very important pleas fix it !!!

**Comment by CocoCC3** [comment]
I'm waiting for the solution

**Comment by Nort721** [comment]
Hmm seems like it only works with latest liquidbounce, will be working on a patch for next updates
