### ISSUE TITLE
Bypass - Speed

### ISSUE THREAD

**Issue by Acenox** [Nort721/GodsEye-Issues#19]
Hello,

1) Test server - GodsEye - Build 13 BETA - Hotfix-1
2) Video : https://youtu.be/wPIoTXHDQvQ
3) Bypass with speed "Mineplex" with cheat "Atmosphere" that you can download here: http://nano-dev.xyz/

Best regards,

**Comment by Nort721** [comment]
Detected by the new speed check that will be released once the recode is out
