### ISSUE TITLE
Fp - NoSwing

### ISSUE THREAD

**Issue by Acenox** [Nort721/GodsEye-Issues#20]
Hello,

1) Test server - GodsEye Build 13 - Hotfix-1
2) Video : https://youtu.be/edqJ3oy56mo
3) The false positive occurs by fight a player.

Best regards,

**Comment by Nort721** [comment]
Try using a vanilla client

**Comment by Nort721** [comment]
write here if it still happeneds with a vanilla client

**Comment by Nort721** [comment]
bug can't be replicated, probably happened when hitting using a client

**Comment by Acenox** [comment]
Odd because it's with a 1.8.8 client.

**Comment by Nort721** [comment]
I found that a lot of hacked clients messes with packets in a way that makes them trigger the NoSwing check, but it never happened to me with a vanilla/optifine clients, if will get more customers having the issue I will reopen it

**Comment by Nort721** [comment]
the issue has succeeded to be replicated, working on a fix

**Comment by Nort721** [comment]
issue fixed
