### ISSUE TITLE
GodsEye Error

### ISSUE THREAD

**Issue by Officiated** [Nort721/GodsEye-Issues#200]
1) GodsEye version: 33 Beta
2) Server Version: 1.8.8
3) ProtocolLib version: 4.5.0
4) Server log: https://pastebin.com/7ZB6bT0c
5) https://youtu.be/S51v0bGvtHE
6) Pretty much after installing GodsEye it didn't load correctly or something, I can do /ge as shown in the video but it doesn't fully work. Also shown in the video is me going on my test server where it works fine.

**Comment by Nort721** [comment]
Please install the correct version of ProtocolLib from GodsEye's spigot page

**Comment by Nort721** [comment]
Please change it and let me know here if it's fixed or not

**Comment by Officiated** [comment]
My bad, the correct version has been installed and the same error is still happening.

**Comment by Nort721** [comment]
Try reinstalling GodsEye, do a server restart

**Comment by Officiated** [comment]
Still getting a similar, if not the same error https://pastebin.com/1GucSH63

**Comment by Nort721** [comment]
So wired, I'll take a look at it next time I seat to work on an update

**Comment by Nort721** [comment]
Can you send your config.yml and checks.yml here, use pastebin

**Comment by Officiated** [comment]
I don't have a config, the plugin isn't loading properly so it isn't generating a config.

**Comment by Nort721** [comment]
Issue discussed in DM's, caused by PerWorldPlugins
