### ISSUE TITLE
Error that might blocks killaura detection?

### ISSUE THREAD

**Issue by jackstaak** [Nort721/GodsEye-Issues#202]
A bug report/issue report should contain:

1) 33B 
2) 1.8.8 FoxSpigot 
3) 4.4.0
4) https://pastebin.com/hX4X3VSa
5) https://pastebin.com/hX4X3VSa + https://youtu.be/RdZb5MWu6ks + https://prnt.sc/stnp0s
6) So I am litterly blatant using killaura and after a while doing that I get kicked with that error popping up in the console.

**Comment by Nort721** [comment]
Try hitting something thats not an NPC

**Comment by jackstaak** [comment]
Yeah I did that and I am getting this error when I get kicked, https://pastebin.com/C8brye0D

**Comment by jackstaak** [comment]
It doesn't kick me for anything at this point just this error that I showed above pops up

**Comment by Nort721** [comment]
Try using paper spigot and see if this kicking error still happens

**Comment by Nort721** [comment]
So when attacking a normal player though, did it flag you?

**Comment by jackstaak** [comment]
Nope attacking a normal player doesn't flag

**Comment by Nort721** [comment]
Ok then what client is it?

**Comment by jackstaak** [comment]
Liquidbounce

**Comment by Nort721** [comment]
This bypass has already been reported in another issue, so Im going to close it now as its a duplicate

**Comment by jackstaak** [comment]
SUre
