### ISSUE TITLE
Lag with 50 bots online, godseye highest plugin (timings)

### ISSUE THREAD

**Issue by jackstaak** [Nort721/GodsEye-Issues#204]
A bug report/issue report should contain:

1) 33B
2) 1.8.8 foxspigot 
3) 4.4.0
4) https://timings.aikar.co/?id=fe835bd63f9a4594b79d24ad18ca5937#plugins
5) https://timings.aikar.co/?id=fe835bd63f9a4594b79d24ad18ca5937#plugins
6) So I botted my server to see at how many people the server would crash, ofcourse I did make timings. I see that at 50 people the tps went to 15 and it was really laggy so I decided to take a look at the timings and I saw that godseye was one of the most lag causing plugins. I was using OQMinebot so those are just "players" standing afk, I was hoping if you could take a look and see it for yourself :)

**Comment by Nort721** [comment]
Hey there, how much ram your server has?

**Comment by Nort721** [comment]
Bot attacks are built to lag your server so its expected, bot attacks contain elements that would help to lag your server, also how much ram you have?

**Comment by Nort721** [comment]
Ok so I have fixed all of the classes that your timings show that are heavy, can't do more than that with these timings, this change should help performance a lot next update
