### ISSUE TITLE
Pleasee improve scaffold check

### ISSUE THREAD

**Issue by DaffyDG** [Nort721/GodsEye-Issues#207]
bypass maybe

1) test server
5) https://www.youtube.com/watch?v=9x6NXOcVJ6k
6) scaffold bypass ?????????????

**Comment by Nort721** [comment]
Will work on it, please mention the client you use

**Comment by DaffyDG** [comment]
for you nort
https://www.youtube.com/watch?v=Pn74Ki7xahM

**Comment by Nort721** [comment]
I see, will see what I can do to patch it, the Tower part of the video (scaffolding up) is not faster then legit building up

**Comment by Nort721** [comment]
Done, upgrades will be released in next version
