### ISSUE TITLE
Multiple issues on 1.15.2

### ISSUE THREAD

**Issue by dorsax** [Nort721/GodsEye-Issues#209]
A bug report/issue report should contain:

1) GodsEye Build 33 Beta
2) Paper version git-Paper-334 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)
3) ProtocolLib v4.5.0
4) Server log: 
[2020-06-12-1.log.gz](https://github.com/Nort721/GodsEye-Issues/files/4770668/2020-06-12-1.log.gz)

5) We recommend sending a video/screenshot of the issue if possible, so we would be able to fix it faster.

The following issues occured, I tested all of them myself, with /ge verbose

Legend: What to do to reproduce - detection triggered
Using scaffolding - Fly TypeG
Using slow falling potion - Fly Type D
Going through waterlogged blocks - Fly Type D
jumpwalking while affected by beacons with Jump2 and Speed2 - Fly Type A
moving with enchanted trident above a lake - TypeG and TypeC
Walking normally with speed2 beacon - Speed TypeF
Killing mobs while standing at a Mobfarm - Killaura TypeC
Killing mobs while standing at a Mobfarm - Reach Type A [edge case]
Sneaking fast or emptying a whole hotbar at the time - Bad Packets [there was no type given]
Enchanted trident plus slow falling potion - Speed TypeE

**Comment by Nort721** [comment]
moving with enchanted trident above a lake - TypeG and TypeC -> you didn't say which check
Killing mobs while standing at a Mobfarm - Reach Type A [edge case] -> if its very rare it probably won't lead to a punishment, and you can just increase the maximum reach in the checks.yml file and would probably prevent the false

**Comment by dorsax** [comment]
Of course, the two trident triggered types are of Fly.
And I had a long conversation with a JackStaak over at Discord about the Reach, I updated the threshold to 
TypeA:
  State: Enabled
  Max: 3.18

But it just got worse and reach detected was about 4.15
So I had to disable it because it was legit. Maybe the fault was more caused by the construction type of the farm? Because that one was the only farm which produced the false flag.

**Comment by Nort721** [comment]
Know that Jack is not a support team so I'm happy he helps you but it would probably be best to first contact the support team in premium-support, I still want you to try and increase max reach to 3.3 because the check does some statistical analysis before it flags and it may still help, its indeed very wired that it happened only in that farm, are you sure that the player was legit?

**Comment by dorsax** [comment]
I will try it with the new threshold.
The false flag tackled multiple players, and I am certain they are legit players (at least some). But I have to note that I am not familiar with your code so I cannot say anything about how this might be wired to that farm or not.

**Comment by dorsax** [comment]
I have a addition:
jumpwalking while affected by beacons with Jump2 and Speed2 - Fly Type A

Fly Type A is also triggered when having said effects and sneaking on a wooden slap, then jumping while sneaking. Is reproducable, no idea if its edgy or has more cases like this.

**Comment by Nort721** [comment]
Hey there, I have fixed some of the issues you have reported here but not all of them, which is why I keep this issue open, can you please retest the issues in here and comment here which onea still cause falses?

**Comment by Nort721** [comment]
I've just tested some of the reports here with the update I'm working on, most of the are fixed for the mob farm stuff next update the reach checks should be way more stable and reliable

**Comment by Nort721** [comment]
Fixed most of the falses here, issue closed because of it is fixed and inactivity of the op
