### ISSUE TITLE
Fp - Fly (A), Movement(Step), Movement(PrefectMove)

### ISSUE THREAD

**Issue by Acenox** [Nort721/GodsEye-Issues#21]
Hello,

1) Test server - GodsEye Build 13 - Hotfix2
2) Video: https://youtu.be/RvTLgjhJ7rU
3) To reproduce the false positive, it is enough to go up a stair then to go down by jumping.

Best regards,

**Comment by Nort721** [comment]
It's not a false positive since you probably can't get punished from it, also you can prevent it with configuration tweaks
