### ISSUE TITLE
[Feature request] Add console commands

### ISSUE THREAD

**Issue by dorsax** [Nort721/GodsEye-Issues#210]
Please add commands to be able to issued by console. 
Some things are better looked up by console, better to be done without anyone to notice he is being watched. It is a normal duty for admins to perform commands on console without being ingame, but GodsEye doesn't provide that yet.

**Comment by Nort721** [comment]
Which commands do you want to be allowed from console, naturally there are commands that are only possible to be executrd ingame

**Comment by dorsax** [comment]
ge verbose
ge logs
also possibility to see the notifications to players like Suspicion and Kick/Ban.

another option would be to create a plain timelined log, in addition to the player based log.

**Comment by Nort721** [comment]
ge verbose allows specific players to see violations ingame, by allowing to execute it from console you want verbose messages to be send in the console?

**Comment by Nort721** [comment]
I have added the option to view punishment logs for the next version, currently not adding the verbose option because I don't think most people would use it since it would be spammy and a lot of work to add
