### ISSUE TITLE
Huge amount of bypasses

### ISSUE THREAD

**Issue by EchoRapidz** [Nort721/GodsEye-Issues#215]
I do not own GodsEye but I wanted to help out.

There's a youtube video on the official test server of a massive amount of bypasses

https://www.youtube.com/watch?v=FVpRUh2tv44

I was thinking about purchasing the anticheat but that video just makes the anticheat look pathetic so I would patch it.

**Comment by Nort721** [comment]
Take a look a the blocked hacks list on spigot, the only bypass you found is for killaura which is already known and I'm working on patching it, all the of the other hacks are not even checked by GodsEye
- phase - not in the blocked hacks list
- step - not in the blocked hacks list (only certain types, we do not claim to block all steps)
- IceSpeed - not in the blocked hacks list
- the jesus check is basic which is known and will be improved over time
- Blink - not in the blocked hacks list
- Server crashers - (its not an AntiCrash plugin)

Yeah the only bypass you found is killaura, all of the other hacks are not in the blocked hacks list which means we have never made checks that are meant to block the cheat, so you have basically bypassed no checks

Stealing my thumbnail and making a video just like my old trailr and making it public is not helping the plugin really, it just seems like you are trying to look smart to be honest while you really only bypassed killaura
