### ISSUE TITLE
Memory leaks during prolonged use of plugin

### ISSUE THREAD

**Issue by Zenya4** [Nort721/GodsEye-Issues#216]
A bug report/issue report should contain:
**GodsEye version**: Build 29 BETA
**Server Version+Fork**: CraftBukkit version git-TacoSpigot-"95870a93" (MC: 1.8.8) (Implementing API version 1.8.8-R0.2-SNAPSHOT)
**ProtocolLib version**: 4.5.0
**Server log**: N/A

**Issue Report**
GodEye tends to use a large amount of RAM when the server has been running for a while, usually after 1 day+ without restarting. This happens even when few to no players are online, and Java GC does not automatically clear the ram used by GodsEye which makes the RAM usage very high. The plugin runs smoothly for a good number of hours, but it eventually eats up all the RAM which I can only attribute to a memory leak. Screenshots are from the memory profiler, and I have DM'ed the heapdump file to Nort on discord. This report was created for tracking progress.

**Screenshots**
https://prnt.sc/t1zmri
https://prnt.sc/t1znck

**Comment by Kurumi78** [comment]
While I wouldnt say this doesnt need fixed, you should usually restart your server daily anyways.

**Comment by Nort721** [comment]
I would generally recommend you to use the latest version of GodsEye, as it contains several optimizations and fixes, also to change your ProtocolLib version to the one recommend in the GodsEye page for 1.8.X -> 1.13.X users

I'll be waiting to get access to the heap dump

**Comment by Nort721** [comment]
I did some memory profiling with latest version and it does not seem like GodsEye leaves leftover memory that stacks up, also the test server is open with GodsEye in it with rare restarts and it seems fine, I'll be waiting to take a look at the heapdump and will try to investigate it further

**Comment by Nort721** [comment]
Hey there just wanted to know if it still happens in the latest version

**Comment by Nort721** [comment]
Issue closed for inactivity
