### ISSUE TITLE
Speed Check TypeE Bug (1.15.2)

### ISSUE THREAD

**Issue by Green-Sickness** [Nort721/GodsEye-Issues#219]
A bug report/issue report should contain:

1) GodsEye version Beta 34
2) Server Version+Fork Paperclip 1.15.2
3) ProtocolLib version: latest
4) Server log: https://hastebin.com/homaduzine.md
5) We recommend sending a video/screenshot of the issue if possible, so we would be able to fix it faster. : https://streamable.com/dq91co
6) A very detailed description of the issue: Speed Check TypeE falses when running and jumping and a Line for some time.

**Comment by Nort721** [comment]
Will make sure to fix it next update, for now disable TypeE
