### ISSUE TITLE
[Feature Request] Remove log entrie

### ISSUE THREAD

**Issue by dorsax** [Nort721/GodsEye-Issues#221]
I would like to suggest the follwing addition:

Add the possibility to remove [one|all] log entries per player.
Natural way via GUI, I would highly suggest a command (at best also console issuable), too.

**Comment by Nort721** [comment]
Sounds like a good idea, will make sure to implement a command and if possible a gui button next update

**Comment by Nort721** [comment]
Added a new command for that, will be released next update
Thanks for the suggestion!
