### ISSUE TITLE
Better compatibility for PerWorldPlugins

### ISSUE THREAD

**Issue by Officiated** [Nort721/GodsEye-Issues#222]
A bug report/issue report should contain:

1) GodsEye version
34 Beta
2) Server Version+Fork
1.8.8
3) ProtocolLib version
4.4.0
4) Server log
https://pastebin.com/U4YnwjTN
https://prnt.sc/t6ix2r
https://prnt.sc/t6oh0c
5) We recommend sending a video/screenshot of the issue if possible, so we would be able to fix it faster.
N/A
6) A very detailed description of the issue
Talked about it a bit in DMs with Nort already but the issue seems to be caused by GodsEye and PerWorldPlugins conflicting or something causing a ton of memory to be used when starting up and therefore preventing GodsEye from properly loading.

**Comment by Nort721** [comment]
Seems like I can't manage to replicate the issue

**Comment by Nort721** [comment]
I did some changes that may help to prevent this error, will release the next version and you should report back if it fixed the error or not

**Comment by Officiated** [comment]
Unfortunately I am still experiencing this error on the newest version of GE. Here is the logs/error with the newest version (not sure if it's changed much, still looks like a memory issue): https://pastebin.com/FZeqTJFc

**Comment by Nort721** [comment]
Hey there, so I did some checking and unfortunatly I cant find much I can do about this, I am going to try finding a solution for this when I seat to work again on next version, but I cant promise anything, I will close this issue if I will not be able to find a fix

I would recommend to try finding finding other ways of getting hand on PerWorldPlugins premium, maybe try contacting the developer

**Comment by Nort721** [comment]
unfortunately, the issue just seems to be a part of PerWorldPlugins
I would recommend to start using BungeeCord or try to find a way to get PerWorldPlugins premium
