### ISSUE TITLE
HighJump Bypass

### ISSUE THREAD

**Issue by Officiated** [Nort721/GodsEye-Issues#223]
A bug report/issue report should contain:

1) GodsEye version
Test Server
2) Server Version+Fork
Test Server
3) ProtocolLib version
Test Server
4) Server log
N/A
5) We recommend sending a video/screenshot of the issue if possible, so we would be able to fix it faster.
https://youtu.be/D16vfsKQn08
6) A very detailed description of the issue
Pretty much doesn't flag for highjump unless the jump is started over or around water which can be shown half way through the video.  
The client used in the video is Wurst 1.8 OF

**Comment by Simmo06** [comment]
I can second this.

**Comment by Nort721** [comment]
Recoded Move TypeH for next version which will detect highjumps
