### ISSUE TITLE
Console Error

### ISSUE THREAD

**Issue by Snowy001** [Nort721/GodsEye-Issues#228]
A bug report/issue report should contain:

1) Build 34 Beta
2) Paper 1.15.2
3) 4.5.1
4) https://hatebin.com/pnjjbitlmr
5) No video or screenshot, just no checks are working and get above error
6) As I said, no checks are working and I get the above error

**Comment by Nort721** [comment]
Try updating to the latest version and comment here if it keeps happening to you

**Comment by Nort721** [comment]
Well that error does not make much sense if it keeps on happening message me on discord and provide a new error message from latest version
