### ISSUE TITLE
Fly & Speed Bypass

### ISSUE THREAD

**Issue by DaffyDG** [Nort721/GodsEye-Issues#229]
A bug report/issue report should contain:

1) 1-5 Test Server
2) https://www.youtube.com/watch?v=Qy4V-V1BExI

**Comment by Nort721** [comment]
The fly got detected for Movement TypeH mostly and speed seems to get detected for NoFall, whats the problem here?

**Comment by DaffyDG** [comment]
what detect ? look https://www.youtube.com/watch?v=wEICWkhPZ28

**Comment by Nort721** [comment]
The speed seems to flag NoFall but very slowly so I will on work that but the fly is getting detected a lot by Move TypeH so the fly is not bypassing

**Comment by DaffyDG** [comment]
it work only 1-85 block radius (fly) without any problem

**Comment by Nort721** [comment]
Seems to be not the case as you flew a very small distance in the video and got detected

**Comment by DaffyDG** [comment]
nope trust give me another 15 minute and I will show you

**Comment by Nort721** [comment]
I will check that out next when I will work on next update anyways

**Comment by DaffyDG** [comment]
yeah good luck nort also check this https://www.youtube.com/watch?v=lz3ED5caE5g

**Comment by DaffyDG** [comment]
i hope next update will detect LiquidBounce killaura

**Comment by Nort721** [comment]
can't get the specific client containing that cheat (idk which sigma this is)
