### ISSUE TITLE
No Console Command Support Error

### ISSUE THREAD

**Issue by SladeHazard** [Nort721/GodsEye-Issues#23]
A bug report/issue report should contain:

1) 1.14.4 Paper
2) 4.5.0-SNAPSHOT
3) https://hastebin.com/vajatugehi.bash
4) N/A
5) this should be easy to fix i don't think godseye support console commands for 1.14.4 paper how to reproduce the error is simple just type /godseye in console :wink:

**Comment by Nort721** [comment]
error solved
