### ISSUE TITLE
Players Planting crops sets off Scaffold Type F

### ISSUE THREAD

**Issue by Ceravia** [Nort721/GodsEye-Issues#231]
A bug report/issue report should contain:

1) GodsEye version: Build 35 BETA
2) Server Version+Fork: PaperSpigot 1.8.8
3) ProtocolLib version: 4.1.0
4) Server log: Flag for scaffold type F
5) We recommend sending a video/screenshot of the issue if possible, so we would be able to fix it faster.
6) A very detailed description of the issue:

When planting crops players flag scaffold f enough times to kick them

**Comment by Nort721** [comment]
first please install the correct version of ProtocolLib from GodsEye's spigot page
