### ISSUE TITLE
Failed Hacks

### ISSUE THREAD

**Issue by N0TR0** [Nort721/GodsEye-Issues#232]
A bug report/issue report should contain:

1) GodsEye version
2) Server Version+Fork
3) ProtocolLib version
4) Server log
5) We recommend sending a video/screenshot of the issue if possible, so we would be able to fix it faster.
6) A very detailed description of the issue

**Comment by N0TR0** [comment]
1. FastEat 
2. AutoGapple
3. Blink
4. Aimbot
5. critical 
6. spider
7. Xray
8. FALSE Scaffold

**Comment by DaffyDG** [comment]
dude nort need video

**Comment by Nort721** [comment]
> 1. FastEat
> 2. AutoGapple
> 3. Blink
> 4. Aimbot
> 5. critical
> 6. spider
> 7. Xray
> 8. FALSE Scaffold

You didn't fill the requested information also:
- AutoGapple is not in the blocked hacks list in the spigot page meaning GodsEye is not built to block this hack
- Blink is not in the blocked hacks list in the spigot page meaning GodsEye is not built to block this hack
- Xray is not in the blocked hacks list in the spigot page meaning GodsEye is not built to block this hack

You didn't provide which scaffold type is falsing so I don't know which scaffold check type I need to checkout

For the other hacks that I guess you mean that are bypassing, you didn't say which client you were using and what settings on this client were bypassing so I also don't know which client I should patch the hack with

Without the requested information about of which version you are using I basically don't know if you have installed the plugin properly, or which versions of Minecraft I need to work with, please make a new issue and do it like we ask, we really didn't ask much
