### ISSUE TITLE
Bypassed Hacks

### ISSUE THREAD

**Issue by yosife** [Nort721/GodsEye-Issues#236]
My friend could bypass: a mode of speed hacks and spider hack was easy To bypass, step, fly for 5 seconds
Hope you fix it and good luck :]

**Comment by Nort721** [comment]
Your friend has probably not been checked by GodsEye

**Comment by Nort721** [comment]
There is no chance he could bypass all of that, DM me on discord and I will explain that to you and how you can check if your is checked or not before testing

**Comment by Nort721** [comment]
Just letting you know that if you wont provide the information that I have asked for this issue will be closed for lack of information in around 5 days

**Comment by Nort721** [comment]
Closed for lack of information
