### ISSUE TITLE
Movement false positive + aimassist

### ISSUE THREAD

**Issue by JazzBroMC** [Nort721/GodsEye-Issues#237]
A bug report/issue report should contain:

1) GodsEye version LATEST
2) Server Version+Fork Stellar spigot 1.8.8
3) ProtocolLib version Latest
4) Server log n/a
5) We recommend sending a video/screenshot of the issue if possible, so we would be able to fix it faster.
6) A very detailed description of the issue
Could you disable movement checks in cobwebs during pvp as it causes false positive. Also my combatlog uses glass wall. When they pvp against it they get banned for movement

Aim assist brings false positive for 1.9+ client users

**Comment by Nort721** [comment]
You need specify the check types that are falsing otherwise I have nothing to work with

**Comment by Nort721** [comment]
Issue closed for Lack of info
