### ISSUE TITLE
BUG's

### ISSUE THREAD

**Issue by microwin7** [Nort721/GodsEye-Issues#238]
A bug report/issue report should contain:

1) 35 BETA
2) 1.8.8 last
3) last for godseye
1 WARN) https://spark.lucko.me/#hp3WGTgmUU
This is right after server restart
2) @Nort721 Tell me, is this a joke? I have enabled debugging permissions in the PermissionEX plugin. For 15-25 seconds. I was looking for a right that players bypass by another plugin. I open it means this latest.log, to see, I see that there is a lot from GodsEye, I see how many checks in a couple of seconds were made, for which I turned on debugging. I find 59 thousand lines of checks. I have 10 players on the server. Do these checks in PEX at least once every 10 seconds and hash the rights for this time

**Comment by Nort721** [comment]
There is nothing to rewrite, GodsEye has to check for certain permissions before every time it wants to check someone
Meaning there is a permission check every condition every time the player is about to be checked
I can make it check for permissions every two minutes when GodsEye updates the profile list but that would make the GodsEye.bypass permission to not affect players instantly
Which will make the plugin harder to use for a lot of people and break some of peoples setup
AntiCheats are just pretty heavy plugins, I can assure you that we are working on optimozations where its possible but well sometimes there is not much I can do about it

**Comment by Nort721** [comment]
Please provide proper timings reports and ram usage report otherwise I cant do much about your complains

**Comment by Nort721** [comment]
issue closed for lack of information, also from my recent memory and CPU scannings I didn't find any issues like that
