### ISSUE TITLE
Bug in my console

### ISSUE THREAD

**Issue by KoopinSmall** [Nort721/GodsEye-Issues#241]
A bug report/issue report should contain:

1) 36 BETA
2) Paper 1.12.2
3) 4.5.0
4) 
[minilog.txt](https://github.com/Nort721/GodsEye-Issues/files/5057735/minilog.txt)

5) everything was happen with the server look in log.
6) so i have practice server 3 paper server which using GE, one of them is a lobby, so two others are practice server which have stable 50 online and they are full, about RAM, im using 7G of ram for 1 practice server and 7G to second server

**Comment by KoopinSmall** [comment]
also pastebin 
https://pastebin.com/xzjuBNuw

**Comment by Nort721** [comment]
please try to redownload ProtocolLib from GodsEye's page, I have updated the links to the correct versions
