### ISSUE TITLE
[Feature Request] Disable Bypass Permission Check

### ISSUE THREAD

**Issue by KoxSosen** [Nort721/GodsEye-Issues#243]
Hello!

In my option it would be a great option in the config, to disable bypass permission checking, or an option to limit, how often GodsEye checks for a bypass permission.

**Comment by Green-Sickness** [comment]
@KoxSosen you could add Perm godseye.bypass false. Or do /ge checkall

**Comment by Nort721** [comment]
Also, I have now checked in the GodsEye code, GodsEye checks the bypass permission every two minutes to all the players on the server, which is really fine I mean in computer terms that's basically nothing to calculate

**Comment by KoxSosen** [comment]
Hm allright. I was only asking for it, becuase when I did /lp verbose, it spams the bypass permission checks like crazy.

**Comment by Nort721** [comment]
I have added an option to disable this specific permission check, you will be able to set it on disabled to prevent the spam
