### ISSUE TITLE
Players getting banned for KillAura

### ISSUE THREAD

**Issue by MrNeeony** [Nort721/GodsEye-Issues#244]
A bug report/issue report should contain:

1) GodsEye version: Build 36 BETA
2) 1.12.2+PaperSpigot
3) ProtocolLib version: 4.5.1.
4) Server log:
https://paste.hostify.cz/?fdf9b3539bf9a4bd#8KXCJwtmtAN12zQLpfqJCFhdDBW8kgPapyaMp1nAFhDd
5) We recommend sending a video/screenshot of the issue if possible, so we would be able to fix it faster.
![2020-08-13_21 39 31](https://user-images.githubusercontent.com/67321863/90179394-ac6b1100-ddad-11ea-8e0b-bcfd2f568715.png)
![2020-08-13_21 39 41](https://user-images.githubusercontent.com/67321863/90179405-af660180-ddad-11ea-8f17-9282ee32ea5c.png)

6) A very detailed description of the issue
Hello, I got error in config, but that's not exactly why I'm writing now.
Players are getting false positive of KillAura, usually they are at XP's farms.

**Comment by Nort721** [comment]
you didn't mention which check type is falsing, therefore, I can't help you, to see the check types you need to enable verbose messages

**Comment by MrNeeony** [comment]
Hello, it is type C
![2020-08-14_14 46 17](https://user-images.githubusercontent.com/67321863/90251512-277c0800-de3e-11ea-82d2-062339bef8d5.png)
