### ISSUE TITLE
New error in my console

### ISSUE THREAD

**Issue by KoopinSmall** [Nort721/GodsEye-Issues#245]
A bug report/issue report should contain:

1) 37 BETA
2) Paper 1.12.2
3) 4.5.1
4) https://pastebin.com/EQ3vszes
5) impossible
6) So in the previous version of the plugin GE gave me error with GodsEyeMoveEvent when GE detects any checks, so in this update godseye gives me error with detect of the Speed/Velocity/Fly , also you can check all in pastebin

**Comment by Nort721** [comment]
This error should have been fixed in the full release, if not please post it in a new issue
