### ISSUE TITLE
Movement false positive

### ISSUE THREAD

**Issue by MrNeeony** [Nort721/GodsEye-Issues#246]
Hello

1) GodsEye version: 37 BETA
2) 1.12.2 PaperSpigot
3) ProtocolLib version: ProtocolLib for 1.8.X -> 1.15.X
4) https://paste.hostify.cz/?836b07f2b901e3f0#Fmbh9qYDTSHmDNrHmhtTrAa1GTqzTEr4iLYVae5qFQVf
5)
![2020-08-18_19 36 32](https://user-images.githubusercontent.com/67321863/90546665-ab115e00-e18a-11ea-8d3a-96292518c518.png)

6) A very detailed description of the issue
Player is getting false positive for Movement type H

**Comment by Nort721** [comment]
How do you know that this is a false positive exactly?

**Comment by Nort721** [comment]
Just letting you know that if you wont reply to comments in about a week the issue will be closed for inactivity

**Comment by Nort721** [comment]
Just letting you know that if you wont reply to comments in about a week the issue will be closed for inactivity

**Comment by Nort721** [comment]
closed for inactivity
