### ISSUE TITLE
GodsEye Console Spam

### ISSUE THREAD

**Issue by KoxSosen** [Nort721/GodsEye-Issues#247]
A bug report/issue report should contain:

1) Build 37 BETA
2) Paper 1.12.2
3) The one that we could downloaded from the anticheat's page. [1.8.x-1.14.x]
4) No console log.
5) https://www.youtube.com/watch?v=jzM-eZuM-bI
6) Permission check spam by godseye, if you check /lp verbose.

**Comment by Nort721** [comment]
I have added a config option so you will be able to enable/disable this permission check
