### ISSUE TITLE
[Suggestion] GeyserMC Support

### ISSUE THREAD

**Issue by JazzBroMC** [Nort721/GodsEye-Issues#248]
Whitelist geysermc players using their floodgates extension from all checks

You can use:
FloodgateAPI.isBedrockPlayer()

**Comment by Nort721** [comment]
Hey there, do you want to basically not check at all, all the players that use this extension?

**Comment by Nort721** [comment]
I have created this quick plugin that uses the GodsEyeAPI to prevent GodsEye from checking BedRock players https://github.com/Nort721/GodsEyeGeyserMC

Here is the jar release: https://github.com/Nort721/GodsEyeGeyserMC/releases/tag/1

**Comment by Nort721** [comment]
I will improve this plugin in the future to allow for more flexibility
