### ISSUE TITLE
Scaffolding triggers movement check aggressively 

### ISSUE THREAD

**Issue by kronus4231** [Nort721/GodsEye-Issues#251]
1) GodsEye version: Build 38 RELEASE
2) Server Version+Fork: paper-1.16.3.jar
3) ProtocolLib version: 4.5.1
4) How to recreate: build a vertical tower with scaffolding and climb up the tower with Godseye watching you

I don’t have logs to share unfortunately but yesterday I was playing on my server and my chat was spammed repeatedly with Suspicion messages about a player. I followed him around and all they were doing was climbing up and down on scaffolding they had built. This happened for 2-3 of the players online and each one of them was just climbing scaffolding.

I think regular scaffolding is throwing a false positive for the movement check

**Comment by Nort721** [comment]
Any chance you have verbose messages? if they got kicked you'll have a punishment log that can be helpful
