### ISSUE TITLE
godseye not working at all

### ISSUE THREAD

**Issue by 32quni8o9WZXD** [Nort721/GodsEye-Issues#254]
A bug report/issue report should contain:

1) im using the most recent version of godseye
2) my server is 1.8-1.16
3) I used the protolibs plugin that was on your spigot
4) /godseye (every command) gives me the same thing when i do just /godseye
so on my server the anticheat isnt keeping anyone from cheating there is no folder for godseye but i can still do /godseye and it gives me /godseye <reload:help> ect 
please try to find a  way to help me

**Comment by Nort721** [comment]
Did any console errors popup when enabling the server or when trying to use commands?
