### ISSUE TITLE
PlaceholderAPI support

### ISSUE THREAD

**Issue by CowzMooMoo** [Nort721/GodsEye-Issues#26]
A bug report/issue report should contain:

1) Server Version+Fork: N/A
2) ProtocolLib version: N/A
3) Server log: N/A
4) We recommend sending a video/a screenshot of the issue if possible, so we would be able to fix it faster. N/A
5) A very detailed description of the issue: Please add PlaceholderAPI support (So Nort Doesnt forget)

**Comment by Nort721** [comment]
Added support, you will be able to use it once next update is released
