### ISSUE TITLE
Movement B / and other false flag

### ISSUE THREAD

**Issue by slumbery** [Nort721/GodsEye-Issues#29]
1) Server Version+Fork: 1.8.9
2) ProtocolLib version: 4.4.0
3) Server log: none
4) We recommend sending a video/a screenshot of the issue if possible, so we would be able to fix it faster:  1( https://streamable.com/xtk3k 2( https://streamable.com/dn05i
5) A very detailed description of the issue: jump over water, thats it / spam break waterlilys when standing on them OR stand on a block and break then form there and get flagged for ONLY Momvent E,

**Comment by Nort721** [comment]
This current issue is fixed, although there are more logic changes I want to make to this check so if you find any similar issues with it know that I am keeping an eye of them
