### ISSUE TITLE
AutoClicker-HitBox-LongJump-KnockBack

### ISSUE THREAD

**Issue by Adriuoda** [Nort721/GodsEye-Issues#3]
A bug report/issue report should contain:

1) 1.8.8-mSpigot
2) ProtocolLib 4.4.0
3) 
4) https://www.youtube.com/watch?v=as5Wke-sVR4&feature=youtu.be
5) Knockback[when player get figth with another player and he's in the air it say's kb] -AutoClicker[i use 18 and 20 cps but it does not detect me] - HitBox[Yep i use it but it's not detect me] - LongJump[I can use long jump] in the video and all of this i was deopped.

**Comment by Nort721** [comment]
Just want you to know that HitBox is undetectable for some clients, I am going to implement a better hitbox check next update tho

**Comment by Adriuoda** [comment]
no problem
just make sure to fix Long Jump - Knock Back
