### ISSUE TITLE
Pingspoof Instant Kick

### ISSUE THREAD

**Issue by Swifti0001** [Nort721/GodsEye-Issues#30]
The test server at 9:55 PM EST
Whenever I join i am instantly kicked for ping spoof. (happened in the most recent server update) and I cannot test the server anymore. I will get kicked instantly. please disable this for the test server. 
![image](https://user-images.githubusercontent.com/45863972/65736289-7bf08a80-e0a8-11e9-9c56-5cf3071acf77.png)

**Comment by Nort721** [comment]
try doing /ge ping <yourname> and tell me what pings you get

**Comment by Swifti0001** [comment]
It's instant. I've been on my home network and now am at my school network and it is still kicking me. I can't test anymore. I've tried with and without a client.

![image](https://user-images.githubusercontent.com/45863972/65776862-ed642380-e110-11e9-9de8-b93275b85943.png)

**Comment by Nort721** [comment]
got it, I will make sure to fix it before the release, thanks for the report
