### ISSUE TITLE
Fly Hack Glitch

### ISSUE THREAD

**Issue by Maxuser4** [Nort721/GodsEye-Issues#32]
A bug report/issue report should contain:

1) Server Version+Fork
1.14.4 Spigot
2) ProtocolLib version
Latest
3) Server log
https://hastebin.com/epevusuyoh.sql
4) We recommend sending a video/a screenshot of the issue if possible, so we would be able to fix it faster.
5) A very detailed description of the issue
I downloaded latest version of GodsEye, downloaded wurst to test it. Got kicked for flying the first time then when it was supposed to ban me, I saw the lightning ban effect but immediately after I just froze and started glitching, I couldn't move my heat and walk. I had to restart the server to fix it.

**Comment by Nort721** [comment]
It seems to be an issue with the ban effect, disable ban effects in the config and try again

**Comment by Nort721** [comment]
Fixed in Build 15 BETA
