### ISSUE TITLE
Server Crash

### ISSUE THREAD

**Issue by laserman120** [Nort721/GodsEye-Issues#33]
Version: 1.14.4 using Paper
ProtocolLib 4.5.0-SNAPSHOT
Logs:
https://pastie.io/xdnrjr.properties
Watchdog Threat ( the part including Gods Eye)
https://pastie.io/blkhfs.md

Description:
Error appeared several times in the console until the server stopped responding/crashed

**Comment by Nort721** [comment]
got it, will make sure to fix it for next update

**Comment by Nort721** [comment]
Fixed in Build 15 BETA
