### ISSUE TITLE
False flags

### ISSUE THREAD

**Issue by DopeDealers** [Nort721/GodsEye-Issues#34]
A bug report/issue report should contain:

1) TacoSpigot+1.8.8
2) proto 4.3.0
3) Server log
4) http://pls-nerf-brigitte.tk/v6hH http://pls-nerf-brigitte.tk/SrF9 http://pls-nerf-brigitte.tk/GodS
5) 
Knockback e: while fighting a player/Entity. walk forward while spam crouching and hitting the entity/It hitting you.

KillAura E: While fighting. rightclick the air or near the player whilst hitting them.

Killaura I: do the same as explain above except strafe the player.

Inventory Actions A: open a plugin related inventory and the plugin closes it for you. instead of you doing it yourself.

Timer: walk on half slab

**Comment by Nort721** [comment]
what type of timer?

**Comment by DopeDealers** [comment]
> 
> 
> what type of timer? also there is no KnockBack typeE

sorry meant A and it was timer A, i showed them in the links

**Comment by Nort721** [comment]
All issues have been fixed except the Knockback one since I am planning on creating a new check for it that will be based on velocity instead of movement, thanks for the report

**Comment by Nort721** [comment]
hey, I am aware that some of the stuff you'v reported here has not been fixed
thats because some of them are more complicated, I will be fixing them when I'll have more time
