### ISSUE TITLE
Exceptions org/apache/commons/lang3/Validate

### ISSUE THREAD

**Issue by entropylaw** [Nort721/GodsEye-Issues#37]
Spigot 1.14.4
ProtocolLib: version: 4.4.0

Updated to BETA15

getting endless spamming of this in console
https://pastie.io/nilcaz.properties

**Comment by Nort721** [comment]
use Build 14 BETA until next update

**Comment by Nort721** [comment]
Try updating your ProcotoclLib to the one mentioned on GodsEye's page
