### ISSUE TITLE
Build 15 Hotfix-1

### ISSUE THREAD

**Issue by Daejangnamu** [Nort721/GodsEye-Issues#39]
A bug report/issue report should contain:

1) Server Version+Fork 
Paper 1.14.4  205build

2) ProtocolLib version 
ProtocolLib 16 build: http://ci.dmulloy2.net/job/ProtocolLib%20Gradle/

3) Server log
https://hastebin.com/zexiwezide.bash

4) We recommend sending a video/a screenshot of the issue if possible, so we would be able to fix it faster.
Video: https://youtu.be/2znThRDMowI

5) A very detailed description of the issue

**Comment by Nort721** [comment]
are you opped?

**Comment by Nort721** [comment]
Also the error your having is fixed in the latest version

**Comment by Daejangnamu** [comment]
not op, /ge verbose enable  and plugin, paper server latest version use

**Comment by Daejangnamu** [comment]
> Also the console error your having is fixed in the latest version, please test if it happens to you again on the latest server

not op, /ge verbose enable and plugin, paper server latest version use

**Comment by Nort721** [comment]
Then try it on the official test server

**Comment by Daejangnamu** [comment]
It works fine on a test server.
I think it's a paper server problem.

**Comment by Nort721** [comment]
> It works fine on a test server.
> I think it's a paper server problem.
> Can you update this issue?

I will make sure to investigate this issue further

**Comment by Daejangnamu** [comment]
Thank you ^_^

**Comment by Nort721** [comment]
The issue cannot be replicated in the latest version, please open a new issue if you do encounter this issue again
