### ISSUE TITLE
Movement B / Fly E falses

### ISSUE THREAD

**Issue by slumbery** [Nort721/GodsEye-Issues#43]
A bug report/issue report should contain:

1) Server Version+Fork 1.8.8
2) ProtocolLib version 4.4.0
3) Server log - 
4) We recommend sending a video/a screenshot of the issue if possible, so we would be able to fix it faster https://streamable.com/kfbx0 / / https://streamable.com/8sa93
5) A very detailed description of the issue pretty clear i guess if you do the same thing as me in the video for the webs you will get also flagged for fly E and sometimes F but thats rare

**Comment by Nort721** [comment]
This should be very easy to fix, will most likely be fixed next update
Thanks for the report!
