### ISSUE TITLE
Health Spoofing

### ISSUE THREAD

**Issue by Swifti0001** [Nort721/GodsEye-Issues#44]
A bug report/issue report should contain:

1) Server Version+Fork
Spigot 1.8.8
2) ProtocolLib version
Up to date
3) Server log
-
4) We recommend sending a video/a screenshot of the issue if possible, so we would be able to fix it faster.
https://downloadmoredownloads.download/i/nmoy.jpg
5) A very detailed description of the issue
Healthspoofing which is in the configuration file doesn't appear to be health spoofing. I find this such a useful thing and I really hope it gets fixed within the next update, as well as NPC Checking.
Also please make the ban animations for kicks as well :)

**Comment by Nort721** [comment]
I will take a look at it!

**Comment by Nort721** [comment]
issue reopened

**Comment by Nort721** [comment]
hopefully closed for the last time now
