### ISSUE TITLE
GodsEye issue

### ISSUE THREAD

**Issue by Rohanm0121** [Nort721/GodsEye-Issues#46]
GodsEye Anti Cheat: 
There are unfortutanely lots of bugs, which i know you can fix ;D,
I am currently running 1.8 - 1.8.9 spigot Server
Protocol LIB - 1.8.X -> 1.13.X
https://www.youtube.com/watch?v=T7oNaLTCPfU&feature=youtu.be
https://www.youtube.com/watch?v=2YA65CPcYUo&feature=youtu.be
This is one of the problems, (BIGGEST ISSUE) 
Also False Kicks such as "Too Much Hacks" When pvping no debuff 
False.  Every time someone pvps over 10 CPS it auto kicks "too much hacks"
Hope you can fix this problem, have lots of faith in this anti cheat. Also when pvping, it locks people in position for "movement"

**Comment by Nort721** [comment]
I cant see one of thw videos, just make them unlisted

**Comment by Nort721** [comment]
You didnt enale verbose so its hard for me to know which checks are falsing
use /ge verbose and retry these falses and comment me here which part you see in chat

**Comment by Rohanm0121** [comment]
Okay thanks buddy, hopefully it should fix the glitches

**Comment by Nort721** [comment]
well doing /ge verbose wont fix the issue but it will give me more information to work with so I will be able to fix it

**Comment by Rohanm0121** [comment]
Dude i'll try give information, but players r online atm, it keeps kicking them i'll have to show you when players come off

**Comment by Nort721** [comment]
for now disable the move and autoclicker checks then

**Comment by Nort721** [comment]
GodsEye has no message in it contains the string "Too Much Hacks"
please open a new issue if you want to report about any other different problems
