### ISSUE TITLE
Console error 

### ISSUE THREAD

**Issue by pewcio** [Nort721/GodsEye-Issues#465]
A bug report should contain:

1) GodsEye version
GodsEye AntiCheat | Advanced Detection Build 52 HotFix-1
2) Server Version+Fork
This server is running Paper version git-Paper-313 (MC: 1.18.2) (Implementing API version 1.18.2-R0.1-SNAPSHOT) (Git: 6f5e6c6)
3) Client Version+Fork
-1.18.2 forge
4) ProtocolLib version
-ProtocolLib 4.8.0
5) Console errors if there are any (using pastebin.com)
-https://pastebin.com/TkvtbrF8
6) We recommend sending a video/screenshot of the issue if possible, so we would be able to fix it faster.
7) A very detailed description of the issue
-Player Join

**Comment by 0xntpower** [comment]
should be fixed in the next version, if it doesn't let us know and we will reopen the issue, I can't be sure because I can't seem to manage to replicate the error
