### ISSUE TITLE
Console Spam

### ISSUE THREAD

**Issue by iazex** [Nort721/GodsEye-Issues#466]
A bug report should contain:

1) Build 52 HotFix-1
2) Papermc 1.18.2 [Cloudnet v3]
3) Console
4) 4.8.0
5) https://pastehub.net/91391edd5b8

**Comment by 0xntpower** [comment]
should be fixed in the next version, if it doesn't let us know and we will reopen the issue, I can't be sure because I can't seem to manage to replicate the error
