### ISSUE TITLE
plugins conflict 

### ISSUE THREAD

**Issue by DarkLigh12** [Nort721/GodsEye-Issues#467]
When a player catches or interacts with a fish from the plug-in PyroFishingPro, GodsEye sends an error in console that it is unable to find that entity with an ID of #### which varies from each fish a player can catch from that other plugin. This is causing my ram to max out and I love Godseye I think its the best anti cheat out there! I don't want to remove GodsEye or PyroFishingPro

**Comment by 0xntpower** [comment]
* error and other details were reported on discord *
I've attempted implementing a fix that seems to work for me in my testing, it should be fixed for the next version
