### ISSUE TITLE
Error console

### ISSUE THREAD

**Issue by microwin7** [Nort721/GodsEye-Issues#47]
Error console:

1) Spigot 1.8.8, Fork noname
2) latest in spigot 1.8.8 with plugin webpage
3) https://pastebin.com/g9PdAKaw
I wanted to configure the bans, they are not issued, looked at the console, saw this

**Comment by Nort721** [comment]
well seems wired, did you use the gui when doing this?

**Comment by microwin7** [comment]
no, it’s even now when the server starts

**Comment by Nort721** [comment]
Well I'll make sure to check that out once I'll be able to, even tho its seems like this error wont affect anything you may want to disable the InventoryActions check if you want to be extra safe

**Comment by microwin7** [comment]
Error related to Citizens plugin. Disabling InventoryActions configuration did not resolve console error

**Comment by microwin7** [comment]
The problem was due to Citizens configuration. I solved the problem

**Comment by microwin7** [comment]
Understood, a conflict with a self-made plugin

**Comment by Nort721** [comment]
I have also fixed some other issues that I found with Citizens
