### ISSUE TITLE
Console error spam

### ISSUE THREAD

**Issue by th3hunter-3** [Nort721/GodsEye-Issues#475]
A bug report should contain:

1) GodsEye version: 54
2) Server Version+Fork: 1.16.5 BungeeCord
3) Client Version+Fork: 1.16.5 Inertia Cheat
4) ProtocolLib version: Latest one 
5) Console errors if there are any (using pastebin.com): https://pastebin.com/Cdwnb44d
6) We recommend sending a video/screenshot of the issue if possible, so we would be able to fix it faster.:
![image](https://user-images.githubusercontent.com/82331116/178795614-741f7fec-7de2-489e-affc-4a37350b2c5f.png)

7) A very detailed description of the issue: This issue is a Console Spam. The console gets full of error messages when atleast 1 player is online. When the player is still the error stops. I've tested with Inertia Client and nothing was detected so I believe the anticheat was completely down even though it said enabled and commands responded.

**Comment by 0xntpower** [comment]
You are not using the correct version of ProtocolLib, as the latest update logs say, you shouldn't use the latest spigot release of ProtocolLib, you need to use the [latest 1.19 experimental version of ProtocolLib](https://ci.dmulloy2.net/job/ProtocolLib/) for latest GodsEye

**Comment by th3hunter-3** [comment]
Oh 1.19 experimental thanks
