### ISSUE TITLE
ProtocolLib Error spamming console

### ISSUE THREAD

**Issue by ThisConvace** [Nort721/GodsEye-Issues#476]
A bug report should contain:

**1) GodsEye version**
54 https://i.imgur.com/UTRSUv1.png
**2) Server Version+Fork**
1.19 Paper jar
**3) Client Version+Fork**
Lunar Client 1.19 
**4) ProtocolLib version**
https://i.imgur.com/snIJf2n.png

**5) Console errors if there are any (using pastebin.com)**
https://paste.helpch.at/aharizudot.php
6) We recommend sending a video/screenshot of the issue if possible, so we would be able to fix it faster.
^^ spamming console
**7) A very detailed description of the issue**
At random, or when punching someone, or when someone is punching me, maybe entities too, this message spams my console. 
I've seen other people have this issue too!

**Comment by ThisConvace** [comment]
This problem is causing people with elytras flying places, as they are loading chunks i assume, the anticheat prob thinks something is up bc it tps them to the ground, it causes players to take damage or fall into lava

**Comment by 0xntpower** [comment]
Should be fixed in the next version
