### ISSUE TITLE
Kicked from boat and anticheat being triggered

### ISSUE THREAD

**Issue by ThisConvace** [Nort721/GodsEye-Issues#477]
A bug report should contain:

1) GodsEye version
Build 54

2) Server Version+Fork
Paper 1.19

3) Client Version+Fork

Lunar 1.19

4) ProtocolLib version
https://i.imgur.com/snIJf2n.png

5) Console errors if there are any (using pastebin.com)
https://paste.helpch.at/aharizudot.php

6) We recommend sending a video/screenshot of the issue if possible, so we would be able to fix it faster.

https://user-images.githubusercontent.com/102564835/182455554-b19af3b4-a2f1-46db-b012-c12e42585ed9.mp4
![unknown](https://user-images.githubusercontent.com/102564835/182455623-faaf56bb-20a0-42a3-bcbd-62307041612c.png)

7) A very detailed description of the issue

When riding a boat and using anything or eating u get kicked, same thing happened when flying over the nether in an elytra. It all relates to that chunk bug. It's kicking players too

**Comment by ThisConvace** [comment]
There is a video in the link above the image

**Comment by ThisConvace** [comment]
https://paste.helpch.at/ozijepawuz.php When hitting players the same error comes. PLEASE FIX THIS. When a player right clicks the air or anything they get kicked out the boat

**Comment by 0xntpower** [comment]
> https://paste.helpch.at/ozijepawuz.php When hitting players the same error comes. PLEASE FIX THIS. When a player right clicks the air or anything they get kicked out the boat

I can't seem to replicate this issue, I tried right-clicking everywhere, hitting other players and getting & out of boats, doesn't seem to trigger this error however I will attempt to implement a fixed depending on the error you sent alone

**Comment by 0xntpower** [comment]
I managed to replicate it, should be fixed in the next version
