### ISSUE TITLE
Purpur Fork Issue

### ISSUE THREAD

**Issue by Kimpka** [Nort721/GodsEye-Issues#478]
1) GodsEye version: Build 55, latest

2) Server Version + Fork: 1.19.2, running Purpur fork (Build #1763), running ViaVersion & ViaBackwards (both 4.4.2 version, issue did last before applying ViaVersion on the server).

3) Client Version + Fork: 1.19, 1.19.1, 1.19.2, issue occurs no matter of a client version, regular client.

4) ProtocolLib version: ProtocolLib v5.0.0-SNAPSHOT-b600

5) Console errors if there are any (using pastebin.com): https://pastebin.com/zChAM9g9

6) We recommend sending a video/screenshot of the issue if possible, so we would be able to fix it faster: There's nothing to record or take a screenshot of.

7) A very detailed description of the issue: It's something related killing mobs/attacking players, it starts to spam the error console while attacking mobs/players, not always but it's the only thing I see it occurs because of. Main issue probably comes from Purpur's fork.

**Comment by 0xntpower** [comment]
This should be fixed in the latest released build (Build 55 HotFox-1)

**Comment by Kimpka** [comment]
Yeah, it got fixed on that update! Thanks a lot!
