### ISSUE TITLE
Console spam 1.8.8

### ISSUE THREAD

**Issue by iJosePlay** [Nort721/GodsEye-Issues#479]
A bug report should contain:

1) GodsEye version: Build 53
2) Server Version+Fork: Paper 1.8.8
3) Client Version+Fork: 1.8.8
4) ProtocolLib version: 4.8.0
5) Console errors if there are any:
https://pastebin.com/S2zbMLuD
6) A very detailed description of the issue:
Just throw the error randomly and spam in the console. It seems to happen more with players that have high latency.

**Comment by 0xntpower** [comment]
A fix will be released in the next version
