### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by GamemodeSurvival** [Nort721/GodsEye-Issues#48]
`09.10 17:44:50 [Server] ERROR Could not pass event PlayerChangedWorldEvent to GodsEye vBuild 17 BETA
09.10 17:44:50 [Server] INFO org.bukkit.event.EventException: null
09.10 17:44:50 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.12.2.jar:git-Spigot-79a30d7-acbc348]
09.10 17:44:50 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.12.2.jar:git-Spigot-79a30d7-acbc348]
09.10 17:44:50 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) [spigot-1.12.2.jar:git-Spigot-79a30d7-acbc348]
09.10 17:44:50 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) [spigot-1.12.2.jar:git-Spigot-79a30d7-acbc348]
09.10 17:44:50 [Server] INFO at net.minecraft.server.v1_12_R1.PlayerList.moveToWorld(PlayerList.java:719) [spigot-1.12.2.jar:git-Spigot-79a30d7-acbc348]
09.10 17:44:50 [Server] INFO at org.bukkit.craftbukkit.v1_12_R1.entity.CraftPlayer.teleport(CraftPlayer.java:541) [spigot-1.12.2.jar:git-Spigot-79a30d7-acbc348]
09.10 17:44:50 [Server] INFO at org.bukkit.craftbukkit.v1_12_R1.entity.CraftEntity.teleport(CraftEntity.java:271) [spigot-1.12.2.jar:git-Spigot-79a30d7-acbc348]
09.10 17:44:50 [Server] INFO at me.keylon.net.events.PlayerHandler.onJoin(PlayerHandler.java:76) [MinecraftEsports-1.0.0.jar:?]
09.10 17:44:50 [Server] INFO at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_222]
09.10 17:44:50 [Server] INFO at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_222]
09.10 17:44:50 [Server] INFO at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_222]
09.10 17:44:50 [Server] INFO at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_222]
09.10 17:44:50 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) [spigot-1.12.2.jar:git-Spigot-79a30d7-acbc348]
09.10 17:44:50 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) [spigot-1.12.2.jar:git-Spigot-79a30d7-acbc348]
09.10 17:44:50 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) [spigot-1.12.2.jar:git-Spigot-79a30d7-acbc348]
09.10 17:44:50 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) [spigot-1.12.2.jar:git-Spigot-79a30d7-acbc348]
09.10 17:44:50 [Server] INFO at net.minecraft.server.v1_12_R1.PlayerList.onPlayerJoin(PlayerList.java:346) [spigot-1.12.2.jar:git-Spigot-79a30d7-acbc348]
09.10 17:44:50 [Server] INFO at net.minecraft.server.v1_12_R1.PlayerList.a(PlayerList.java:166) [spigot-1.12.2.jar:git-Spigot-79a30d7-acbc348]
09.10 17:44:50 [Server] INFO at net.minecraft.server.v1_12_R1.LoginListener.b(LoginListener.java:159) [spigot-1.12.2.jar:git-Spigot-79a30d7-acbc348]
09.10 17:44:50 [Server] INFO at net.minecraft.server.v1_12_R1.LoginListener.e(LoginListener.java:57) [spigot-1.12.2.jar:git-Spigot-79a30d7-acbc348]
09.10 17:44:50 [Server] INFO at net.minecraft.server.v1_12_R1.NetworkManager.a(NetworkManager.java:233) [spigot-1.12.2.jar:git-Spigot-79a30d7-acbc348]
09.10 17:44:50 [Server] INFO at net.minecraft.server.v1_12_R1.ServerConnection.c(ServerConnection.java:140) [spigot-1.12.2.jar:git-Spigot-79a30d7-acbc348]
09.10 17:44:50 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:845) [spigot-1.12.2.jar:git-Spigot-79a30d7-acbc348]
09.10 17:44:50 [Server] INFO at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigot-1.12.2.jar:git-Spigot-79a30d7-acbc348]
09.10 17:44:50 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot-1.12.2.jar:git-Spigot-79a30d7-acbc348]
09.10 17:44:50 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot-1.12.2.jar:git-Spigot-79a30d7-acbc348]
09.10 17:44:50 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_222]
09.10 17:44:50 [Server] INFO Caused by: java.lang.NullPointerException
09.10 17:44:50 [Server] INFO at godseye.J.a(J.java:387) ~[?:?]
09.10 17:44:50 [Server] INFO at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_222]
09.10 17:44:50 [Server] INFO at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_222]
09.10 17:44:50 [Server] INFO at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_222]
09.10 17:44:50 [Server] INFO at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_222]
09.10 17:44:50 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot-1.12.2.jar:git-Spigot-79a30d7-acbc348]`

And everytime server restarts, I have to do /ge cp and enable all checks. I also blocked the command /ge to players(using preprocesscommandevent) and it still sends the message. Only saying this here because it is only this plugin it does it with.

**Comment by Nort721** [comment]
Error fixed, the fix will be released next version, if you need to enable the checks every time you might want to reset your config? if it still happends I'll need more information
For the /ge command is hard to block intentionally

Thanks for the report

**Comment by Nort721** [comment]
The main Issue is fixed, please open another issue if you have more info to give about the other problems that you have complained about
