### ISSUE TITLE
1.14.4 Bot Check 

### ISSUE THREAD

**Issue by SladeHazard** [Nort721/GodsEye-Issues#49]
1) 1.14.4 Paper
2) 4.5.0-SNAPSHOT
3 ) https://hastebin.com/puloguruva.md
4) https://www.youtube.com/watch?v=XUpVR5X_SM8&feature=youtu.be
5) So basically to reproduce this error you have to load godseye on 1.14.4 (Paper) and type /godseye profile [player] and then run bot check on him and the errors will spam in the console and there is no bot appearing in-game

**Comment by SladeHazard** [comment]
https://hastebin.com/ubasejofij.rb

**Comment by SladeHazard** [comment]
oh and btw i tried using killaura while the bot  was spawned (just to test if the both actually spawns which is invisible or not) it's doesn't spawn and my killaura hits it 0 times

**Comment by Nort721** [comment]
Issue closed since it's considered outdated, the Bot check has been changed to support 1.8.X - 1.13.2 only
