### ISSUE TITLE
groundspoof / (airwalk?) falses 

### ISSUE THREAD

**Issue by slumbery** [Nort721/GodsEye-Issues#5]
1) Server Version+Fork: Spigot 1.13.2
2) ProtocolLib version: 4.4.0
3) Server log: - 
4) We recommend sending a video/a screenshot of the issue if possible, so we would be able to fix it faster: https://streamable.com/t51cx

5) A very detailed description of the issue: so when you just walk on oak wood blocks (ID: Minecraft:oak_wood) it flaggs for groundspoof and sometimes airwalk / equalrotations this is on any ''wood'' block and not on blocks like normal oak logs now the slabs when you place slabs like this https://prnt.sc/op92bz it flags for groundspoof (yes only grondspoof) this is for all slabs, i found them by just running around the spawn

**Comment by Nort721** [comment]
We are having trouble replicating the bug, please post your full plugin list

**Comment by Nort721** [comment]
ok we've found the reason that this is happening, it's going to be a big fix and will probably delay Build 12's release but its going to be an important one
