### ISSUE TITLE
Timer Render

### ISSUE THREAD

**Issue by microwin7** [Nort721/GodsEye-Issues#50]
Error render due to Timer:

Spigot 1.8.8 LATEST
ProtocolLib 4.4.0-b421
Cleanly console logs
When teleportation occurs, over a long distance, in one world. Server erroneously blocks packets. Checked the way to disable all plugins. Then they suggested what could be in Timer. After shutdown, everything became good right away
https://imgur.com/a/X6AcIYT

Configuration:
```
Timer:
  # Enabled/Disabled
  Check: Enabled
  # Max timer violations, amount of violations before punishment
  # (default: 35)
  Max violations: 35
  # Teleport the player down
  Cancel: Enabled
  # After how many violations start cancelling
  Cancel violations: 3
  # A bit unstable check but super fast and detects very low timers
  # and a lot of other hacks
  TypeA: Enabled
  # More stable but slower check
  TypeB: Enabled
  # When a player reaches one of the violations amounts from this list the staff will be alerted
  Alert violations:
    - 11
    - 22
    - 30
  # Should kick for timer hacking
  Kick player: Disabled
  # Should ban for timer hacking
  Ban player: Enabled
```

**Comment by Nort721** [comment]
Well I don't see a reason for this to be related to GodsEye, teleporting long distances is a known Minecraft issue for rendering

Can you maybe post your plugin list, please?

**Comment by microwin7** [comment]
Plugman, Essentials, PermissionEx, ProtocolLib, Godseye

**Comment by Nort721** [comment]
well I don't really know I will try finding a connection between rendering and the Timer check

**Comment by Nort721** [comment]
issue found to not be in GodsEye by the user
