### ISSUE TITLE
NoFall falsely

### ISSUE THREAD

**Issue by microwin7** [Nort721/GodsEye-Issues#51]
Spigot 1.8.8 LATEST
ProtocolLib 4.4.0-b421
https://imgur.com/a/1x3mSXv

**Comment by Nort721** [comment]
well thats why NoFall TypeB (GroundSpoof) is commented as unstable in the config and disabled by default, I am going take a look at it thought

**Comment by Nort721** [comment]
on ok nvm there was a config mistake
