### ISSUE TITLE
MULTIPLE PVP CHECKS FALSE POSITIVE ON 1.14.4 PAPER

### ISSUE THREAD

**Issue by SladeHazard** [Nort721/GodsEye-Issues#52]
1.14.4 Paper
4.5.0-SNAPSHOT
1. You can reproduce (movement check false) by jumping while pvping and strafing at the same time now you might think who does that while pvping well guess what pros like me do i'm hypixel 150 star on bedwars the reason why you jump is to get Crits and you basically know what strafe is so yeah
2. You can reproduce (Knockback check false) by w-tapping. What is W-TAP? https://www.youtube.com/watch?v=HKcDSmeJcfM
3. You can reproduce (regen) by going into lava while pvping and eating a gap i forgot just try both 2nd way i think its possible to do this suffocate in a block 3rd way: go in lava while golden enchanted apple activated
4. You can reproduce (timer check false) by right clicking a full set of armor very fast this only happend to me once when server was lagging just a little so don't think it should be reproduceable just wait for the video just to prove these false positives i need a video which should be here by tmr 

Anyways there are the checks which i check immediately after purchasing a new anticheat and testing it if its useable for the network because the first thing players get false banned is by legit god pvp skills  thats the only different between anticheats and watchdog that watchdog never false bans god pvpers like me anyways i hope this get fixed asap.

LITERALLY TOO LAZY TO RECORD A VIDEO MY WIFI IS GOING CRAZY RIGHT NOW WILL MAKE A VIDEO TMR UNTIL THEN TICKET IS ON HOLD

**Comment by Nort721** [comment]
Please change the first video to unlisted instead of private since when its private I cant watch it

**Comment by Nort721** [comment]
Also please provide the Type of the checks you report about, you can see parts by running /ge verbose

**Comment by SladeHazard** [comment]
> Please change the first video to unlisted instead of private since when its private I cant watch it, Also thanks for the effort put into this ticket

oh about the video that isn't the hack video its of the old bot check bug i'll remove it i will make a video on reproducing false-checks tmr not on pc rn

**Comment by Nort721** [comment]
no problem, take your time

**Comment by Nort721** [comment]
any video?

**Comment by SladeHazard** [comment]
... i informed you about this on discord you probably didn't read it no problem this is no longer false turns out that GODSEYE was false flagging players for pvping because the server tps was dropping to 13  and you told me that godseye tps protection is not good atm so thats why this happend no longer happening after i removed a plugin on my server causing massive tps drops its also a problem with 1.14.4 paper massive lag spikes  you can close this ticket

**Comment by Nort721** [comment]
I see, I will make sure to improve the TPS protection anyways for these checks, thanks for the report
