### ISSUE TITLE
1.14.4 MORE BUGS

### ISSUE THREAD

**Issue by SladeHazard** [Nort721/GodsEye-Issues#53]
1) 1.14.4 Paper
2) 4.5.0 Snapshot
3) https://hastebin.com/winizaneso.md
4) So the new godseye version came out 18 beta i wanted to test it started my server with 10gb ram on my pc and logged in with a alt on vanilla 1.12.2 and logged in with another account on badlion 1.8.9 the second i joined the server i was lagging scoreboard was stuck probably my wifi or something while my other acc was running fine then i got kicked for hacking and some errors appeared in my console and on my other account it said i was detected for timer so last time i did report timer false positive so yeah i don't think this should be reproduceable but i did find timer false positives while pvping before so i guess you wil lsee when i get the video tmr just wanted to report this so you could see the error and tell if you can just fix it without anything needed

**Comment by SladeHazard** [comment]
LOL more bugs so a second after i relogged with my another account and these error came: https://hastebin.com/otimobomis.rb

**Comment by Nort721** [comment]
ok seems like its just a console error combined with a Timer false positive I found time is sensitive with laggy players, I have most likely fixed the second issue you sent but the first one looks very wired and I can't seem to replicate it

Also, can you write down what ProtocolLib version you are using?

**Comment by SladeHazard** [comment]
> ok seems like its just a console error combined with a Timer false positive I found time is sensitive with laggy players, I have most likely fixed the second issue you sent but the first one looks very wired and I can't seem to replicate it
> 
> Also, can you write down what ProtocolLib version you are using?

[20:35:52 INFO]: [PlugMan] Plugin Information: ProtocolLib
[20:35:52 INFO]: - Version: 4.5.0-SNAPSHOT
[20:35:52 INFO]: - Author(s): dmulloy2, comphenix
[20:35:52 INFO]: - Status: Enabled

**Comment by Nort721** [comment]
I have just released an update that Should fix the second error you have provided, as to the first I could not seem to replicate it
I will leave this issue open and will do a future investigation on this error log

**Comment by Nort721** [comment]
Any updates about a video?

**Comment by SladeHazard** [comment]
this issue was fixed? the error i sent and turns out the lag was from one of my plugins that i removed so please close this ticket.
