### ISSUE TITLE
Falses On Falses

### ISSUE THREAD

**Issue by coolpvpv1** [Nort721/GodsEye-Issues#54]
A bug report/issue report should contain:

1) Server Version+Fork idk its official test server
2) ProtocolLib version idk its official test server
3) Server log Watch The Video
4) We recommend sending a video/a screenshot of the issue if possible, so we would be able to fix it faster. https://streamable.com/00nok
5) A very detailed description of the issue
Watch the video to see how i false aimassist a hitbox b badpackets g inventoryactions b and a and maybe other checks i haven't falsed yet who knows lol

**Comment by Nort721** [comment]
Well there is a whole system that analyses verbose alerts
You guys just don't understand how it works, that you were able to flag a check does not mean its a false positive, thats why they are called suspects, some of these are falses and I'll make sure to fix them but a false positive is only when you were able to get kicked from a check, until then don't waste my time please
