### ISSUE TITLE
1.8 players on 1.12 server

### ISSUE THREAD

**Issue by GamemodeSurvival** [Nort721/GodsEye-Issues#55]
Omg this plugin false flags so much. It keeps banning them for no swing because they are on 1.8

**Comment by GamemodeSurvival** [comment]
Another thing I forgot to add: Disabling checks doesn't do anything. It still watches those checks, and turning off the plugin via the gui doesnt do anything.

**Comment by Nort721** [comment]
GodsEye Currently does not support any ProtocolHack plugin except for ViaVersion,
As for the issue of disabling checks, I will look into it

**Comment by GamemodeSurvival** [comment]
> GodsEye Currently does not support any ProtocolHack plugin except for ViaVersion,
> As for the issue of disabling checks, I will look into it for now use the config file + restart to disable checks

I am using via version...

**Comment by Nort721** [comment]
> > GodsEye Currently does not support any ProtocolHack plugin except for ViaVersion,
> > As for the issue of disabling checks, I will look into it for now use the config file + restart to disable checks
> 
> I am using via version...

Using ViaVersion you will not able to login to a 1.12 server with 1.8 clients so you must be doing another protocolhack which is not supported

**Comment by GamemodeSurvival** [comment]
> > > GodsEye Currently does not support any ProtocolHack plugin except for ViaVersion,
> > > As for the issue of disabling checks, I will look into it for now use the config file + restart to disable checks
> > 
> > 
> > I am using via version...
> 
> Using ViaVersion you will not able to login to a 1.12 server with 1.8 clients so you must be doing another protocolhack which is not supported
> 
> ViaVersion lets only login with newer clients to an older server version

Via Rewind + Via Backwards

**Comment by Nort721** [comment]
well as I said, GodsEye currently support ViaVersion, ViaBackward and ViaRewind are not ViaVersion
