### ISSUE TITLE
Sweeping Edge being detected as Kill Aura

### ISSUE THREAD

**Issue by Bluefire123** [Nort721/GodsEye-Issues#57]
Plugin Version: Build 19 BETA
Server Version: Paper git-Paper-221 (1.14.4)
ProtocolLib version: v4.5.0-SNAPSHOT
Server Log: https://pastebin.com/XhCr2FHf (The errors happen towards the end but i included the entire server log)

Video showing bug: https://www.youtube.com/watch?v=9BYgUV4oPl8

Although the video does not show the bug being detected as Kill Aura, in other tests the plugin has said that Kill Aura is being detected.

The only plugins on the server are GodsEye and ProtocolLib.

**Comment by Nort721** [comment]
Hey there, I have fixed the error for the next version but to fix the Killaura false positive that you have reported I need to know what part of Killaura is doing the false, please run /ge verbose and send me here the type shows to you in chat

**Comment by Bluefire123** [comment]
Killaura TypeC
