### ISSUE TITLE
Ban Effect Request

### ISSUE THREAD

**Issue by byZahory** [Nort721/GodsEye-Issues#6]
Hey,

Maybe is it possible to add a new Ban Effect like one of the following two: (Or both?)

https://www.youtube.com/watch?v=931kJj1imrI
https://www.youtube.com/watch?v=JMNoFoo_CYM

**Comment by Nort721** [comment]
well we hade a few requests for new ban effects, we are currently not putting this requests in our highest priority since we have more argent stuff but that does not mean we would not add one in the future, but it would most likely won't be added in the 2 - 3 next updates
