### ISSUE TITLE
flase Fly (Type A) and Movement (Step) report

### ISSUE THREAD

**Issue by slumbery** [Nort721/GodsEye-Issues#7]
A bug report/issue report should contain:

1) Server Version+Fork: 1.13.2
2) ProtocolLib version: 4.4.0
3) Server log: - 
4) We recommend sending a video/a screenshot of the issue if possible, so we would be able to fix it faster: https://streamable.com/oh2o5
5) A very detailed description of the issue: its pretty simple as you can see in the clip just jump over water at you will get flagged for fly type A and movement Step found this when i shaw some1 else getting this flag when we were pvping on the test server so its for 1.8.8 and 1.13.2

**Comment by Nort721** [comment]
Thank you for reporting it, I'll release a HotFix as false as I can!
