### ISSUE TITLE
ChestStealer (Type B) false

### ISSUE THREAD

**Issue by PiiSaba** [Nort721/GodsEye-Issues#70]
A bug report/issue report should contain:

1) Server Version+Fork: The official testing server's.
2) ProtocolLib version: The official testing server's.
3) Server log: I don't have it because I found it on the official testing server.
4) We recommend sending a video/a screenshot of the issue if possible, so we would be able to fix it faster.: https://streamable.com/pevbq
5) A very detailed description of the issue: The video shows how to recreate the false.

**Comment by Nort721** [comment]
I've changed it so you need to fail the check more then once in a row to flag, it will still be possible to flag if you try really hard unfortunately with the kind of logic TypeB uses it's very hard to make the 100% safe from falses and still catch ChestStealers fairly quickly, you can disable TypeB in the config or just set Max VL and cancel VL to be a bit higher and I doubt someone will be able to get falsely kicked/banned from it (considering flags gets cleaned automatically) while casually playing and combined with TypeA you will still have some protection from ChestStealer
Thanks for reporting, have a good day
Best regards
~ Nort721
