### ISSUE TITLE
KnockBack (Type A) false

### ISSUE THREAD

**Issue by PiiSaba** [Nort721/GodsEye-Issues#71]
A bug report/issue report should contain:

1) Server Version+Fork: The official testing server's.
2) ProtocolLib version: The official testing server's.
3) Server log: I don't have it because I found it on the official testing server.
4) We recommend sending a video/a screenshot of the issue if possible, so we would be able to fix it faster.: https://streamable.com/1l5l2
5) A very detailed description of the issue: The video shows how to recreate the false.

**Comment by PiiSaba** [comment]
YouTube0099 was using Vanilla 1.8.8.

**Comment by PiiSaba** [comment]
I can send you a link that is the no cut version if you don't believe me.

**Comment by Nort721** [comment]
I have made the check more lag resistant, hopefully, will solve this
