### ISSUE TITLE
AutoClicker (Type F) false

### ISSUE THREAD

**Issue by PiiSaba** [Nort721/GodsEye-Issues#72]
A bug report/issue report should contain:

1) Server Version+Fork: The official testing server's.
2) ProtocolLib version: The official testing server's.
3) Server log: I don't have it because I found it on the official testing server.
4) We recommend sending a video/a screenshot of the issue if possible, so we would be able to fix it faster.: https://streamable.com/jndny
5) A very detailed description of the issue: Do jitter click!!!

**Comment by Nort721** [comment]
The issue is already known and will be fixed next version, thanks for reporting though!
