### ISSUE TITLE
Speed (Type A) false

### ISSUE THREAD

**Issue by PiiSaba** [Nort721/GodsEye-Issues#73]
A bug report/issue report should contain:

1) Server Version+Fork: The official testing server's.
2) ProtocolLib version: The official testing server's.
3) Server log: I don't have it because I found it on the official testing server.
4) We recommend sending a video/a screenshot of the issue if possible, so we would be able to fix it faster.: https://streamable.com/kc1pv
5) A very detailed description of the issue: Spam spacebar as fast as you can when there is a block above you!

**Comment by Nort721** [comment]
This check is not supported anymore since it's very old and not really useful, you can disable it and you will have no problem for detecting speed
