### ISSUE TITLE
Tower (Type A) false

### ISSUE THREAD

**Issue by PiiSaba** [Nort721/GodsEye-Issues#78]
A bug report/issue report should contain:

1) Server Version+Fork: 1.8.8 Spigot
2) ProtocolLib version: 4.4.0
3) Server log: none
4) We recommend sending a video/a screenshot of the issue if possible, so we would be able to fix it faster.: https://streamable.com/j9fj0
5) A very detailed description of the issue: The video shows how to recreate the false.

**Comment by Nort721** [comment]
This is too rare and will probably not lead to punishment, if it will you can just increase max VL and with the AutoMated flags clear it will most likely not lead to a punishment
