### ISSUE TITLE
No notifications

### ISSUE THREAD

**Issue by byZahory** [Nort721/GodsEye-Issues#8]
A bug report/issue report should contain:

1) Spigot 1.8.8
2) 4.4.0
3) There are no errors in the log. (https://pastebin.com/KV8KjfjC)
4) I've send it on Discord.
5) It does not send any normal notifications to the staff. Only the verbose notifcations are sent.

Config: https://pastebin.com/BKR27yhe

**Comment by Nort721** [comment]
Try updating to the latest version on spigot (also reset your config)

**Comment by Nort721** [comment]
the issue cannot be replicated and exist only at your server which leading me to believe that it has something to do with your server and not a problem in GodsEye, please try checking your permissions deeper, do not use * for this, add GodsEye.notify instead try maybe trying a different permissions plugin like PermissionsEX, try opening a local server and see if people get the alerts there, if the issue still exists please open a new issue and resend me your plugin list
