### ISSUE TITLE
Rare? InventoryActions (Type A) false

### ISSUE THREAD

**Issue by PiiSaba** [Nort721/GodsEye-Issues#80]
A bug report/issue report should contain:

1) Server Version+Fork: 1.8.8 Spigot
2) ProtocolLib version: 4.4.0
3) Server log: none
4) We recommend sending a video/a screenshot of the issue if possible, so we would be able to fix it faster.: https://streamable.com/oizdp
5) A very detailed description of the issue: Running, Open ur inventory and then throw an item as fast as you can.

**Comment by Nort721** [comment]
Too rare to cause a punishment, but I will be taking a look at what can be done to fix it

Thanks for reporting!
