### ISSUE TITLE
SkywarsX support

### ISSUE THREAD

**Issue by Thobov** [Nort721/GodsEye-Issues#82]
A bug report/issue report should contain:

1) Server Version+Fork: N/A
2) ProtocolLib version: N/A
3) Server log: N/A
4) We recommend sending a video/a screenshot of the issue if possible, so we would be able to fix it faster: N/A
5) A very detailed description of the issue: It would be very nice if there will be support for SkywarsX by Wazup92 who also made EggwarsX. Wazup92 has provided an API at the spigot page of SkywarsX.

**Comment by Nort721** [comment]
Added
