### ISSUE TITLE
Chunk not loading

### ISSUE THREAD

**Issue by Kriiista** [Nort721/GodsEye-Issues#83]
A bug report/issue report should contain:

- PaperSpigot 1.8/1.7
- ProtocolLib 4.4.0
- No problem
- When the players are teleported to the arens (which are far from spawn) sometimes, the chunks don't load for them. Even if they get teleported are if they use an enderpearl to try.

**Comment by Nort721** [comment]
What version of GodsEye you are using?

**Comment by Nort721** [comment]
recent changes may have solved this one, please test it on newer versions
