### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by btc2628** [Nort721/GodsEye-Issues#84]
A bug report/issue report should contain:

1) GodsEye version: Build 22 Beta
2) Server Version+Fork: PaperSpigot 1.8.9
3) ProtocolLib version: 4.4.0
4) Server log: Task #(number in the millions) for GodsEye Build 22 Beta granted an exception for java.lang.NullPointerException

5) We recommend sending a video/screenshot of the issue if possible, so we would be able to fix it faster.

<img width="684" alt="Screen Shot 2019-11-26 at 10 54 33 AM" src="https://user-images.githubusercontent.com/37251868/69656703-045abf80-1047-11ea-91d9-37c6b8fb4e73.png">

6) A very detailed description of the issue

the above repeated what seemed like indefinitely, lmk if there's any other information I can provide

**Comment by Nort721** [comment]
unfortunately the stack trace provided in your picture has no useful info for me to find the error, any chance you have got a more detailed version of it?
