### ISSUE TITLE
Your GodsEye Copy is not activated for some reason, please contact Nort721 for manual activation

### ISSUE THREAD

**Issue by Ami-OS** [Nort721/GodsEye-Issues#86]
A bug report/issue report should contain:

1) GodsEye version: Build 22 BETA
2) Server Version+Fork: This server is running CraftBukkit version git-Spigot-56f8471-ccd47a5 (MC: 1.14.4) (Implementing API version 1.14.4-R0.1-SNAPSHOT)
3) ProtocolLib version: 4.4.0
4) Server log:
```
19:12:52 [Server] [GodsEye] Enabling GodsEye vBuild 22 BETA
19:13:08 [Server] GodsEye Your GodsEye Copy is not activated for some reason, please contact Nort721 for manual activation
19:13:08 [Server] [GodsEye] Disabling GodsEye vBuild 22 BETA
19:13:08 [Server] [GodsEye] GodsEye has been disabled
```
5) We recommend sending a video/screenshot of the issue if possible, so we would be able to fix it faster.
![2019-12-01 19-39-34 cut](https://user-images.githubusercontent.com/58389183/69913453-040d5a80-1473-11ea-96b8-29940870efb1.png)

6) A very detailed description of the issue:
Looks like activation failed,What activation server does this plugin need to connect to?
I should open a port on the firewall?
Or which activation server address should i allow in firewall?
(I am using [DMZ network])

**Comment by Nort721** [comment]
Hey there, Thanks for the detailed report! I have activated your copy!
