### ISSUE TITLE
Get kicked in combat

### ISSUE THREAD

**Issue by NORTBE** [Nort721/GodsEye-Issues#90]
A bug report/issue report should contain:

1) last
2) onlinemode=false / 1.8.9 / Paper / bungee / no viaversion
3) 4.4.0
4) https://pastebin.com/m7uCm6qC 
5) ---
6) I installed plugin and do not configure anything just install and start ac checks testing. when i start after some time i get kicked on combat start (After some hits, almost instant) but i think its my problem (with client or e.t.c) but after i recon and continue test your ac i get 2 more the same kicks.

Sorry for my language skills, im from Ukraine :smiley:

**Comment by Nort721** [comment]
Hey there, I will need to know what client version you used and I need you to enable verbose and tell me what checks and what check types have flagged you

**Comment by Nort721** [comment]
The error in your post has been fixed, now I only need to know what check and check part caused the false positive and all the other info I asked above
