### ISSUE TITLE
Ban effects issue?

### ISSUE THREAD

**Issue by NORTBE** [Nort721/GodsEye-Issues#92]
1) - lastest
2-5) - doesnt matter
6) Ban effect only work if player adds to ban wave and doesnt get kicked again or relogged (if ban wave comes almost no one will see the ban effect) I test it if player adds to ban wave and relog = instant ban on wave run without effect, or if he gets kicked by other plugin/ac or even manual exit will stop ban effect, just an insta ban.

And what about add feature to configure ban effect to kick effect (dont really wanna to use ban waves, but it has cool effect and i wanna use it for every kick)

Sorry for language skillz xD

**Comment by Nort721** [comment]
Will consider adding effects also to kicking, for the ban wave system I will see how I can change it to make more sense

**Comment by Nort721** [comment]
Fixed the ban effect logic issue, will consider adding the kick effects
Thanks for your report, please open a new issue if you found the issue happening again
