### ISSUE TITLE
Activation Failure | GodsEye version 24 |

### ISSUE THREAD

**Issue by Sanchyro** [Nort721/GodsEye-Issues#94]
1) Build 24 BETA
2) 1.8.8-R0.1-SNAPSHOT PaperSpigot
3) Protocollib 4.4.0
4) http://prntscr.com/qf4g9k
5) not needed
6) When we try to load the plugin it says "Your GodsEye copy is not activated for an unknown reason, please contact Nort721 for manual activation".

**Comment by Nort721** [comment]
I have activated your copy, should work now!
