### ISSUE TITLE
EntityDamageBytEntityEvent NullpointerException

### ISSUE THREAD

**Issue by Sanchyro** [Nort721/GodsEye-Issues#95]
1) 24 BETA
2) PaperSpigot 1.8.8-R0.1-SNAPSHOT
3) 4.5.0
4) http://prntscr.com/qgyvk8
5) http://prntscr.com/qgyvk8, This error occures whenever a entity gets damaged by another entity.
6) http://prntscr.com/qgyvk8

**Comment by Nort721** [comment]
I'm pretty sure I have located the issue, although I can't replicate it so please open a new issue if it still happens with the next version

**Comment by SladeHazard** [comment]
> I'm pretty sure I have located the issue, although I can't replicate it so please open a new issue if it still happens with the next version

also happens with me paper 1.12.2 was about to open aticket but nah also i think it only happens on paper occured while players were dueling with Duels plugin https://hastebin.com/yedohuferu.cs
