### ISSUE TITLE
Error Console

### ISSUE THREAD

**Issue by microwin7** [Nort721/GodsEye-Issues#96]
Spigot 1.8.8 LATEST
ProtocolLib 4.4.0-b421
Cleanly console logs
Only if on check Timer

There is a command block (warp arena @a [r = 2])   Which teleports about 200 blocks. The warp team works through essentials. Causes a rendering problem.
https://pastebin.com/XW085pNX

**Comment by Nort721** [comment]
Please specify the GodsEye version you were using when the issue happened

**Comment by microwin7** [comment]
24-BETA

**Comment by Nort721** [comment]
recent changes may have solved this one, please test if it happens to you again, we may be able to solve this way faster this time if it appears again
