### ISSUE TITLE
Console Spam on Player Quit 1.15.1

### ISSUE THREAD

**Issue by ColaIan** [Nort721/GodsEye-Issues#97]
A bug report/issue report should contain:

1) GodsEye version | Build 24 BETA
2) Server Version+Fork | Paper 1.15.1 #32
3) ProtocolLib version | 4.5.0
4) Server log | https://pastebin.com/raw/SLHzUu6B
5) We recommend sending a video/screenshot of the issue if possible, so we would be able to fix it faster. | N/A
6) A very detailed description of the issue | When I leave the server, there is a FieldAccessException which is caused by "No field with type int exists in class PacketPlayOutKeepAlive"

**Comment by Nort721** [comment]
1.15.1 support has not been released yet
