### ISSUE TITLE
MINING ERROR

### ISSUE THREAD

**Issue by SladeHazard** [Nort721/GodsEye-Issues#99]
A bug report/issue report should contain:

1) Build 24 BETA
2) Paper 1.12.2
3) 4.4.0
4) https://pastebin.com/QEX3hSHk 
5) We recommend sending a video/screenshot of the issue if possible, so we would be able to fix it faster.
6) The error randomly occurs sometimes has happend 2 times now when a player is mining in my server.

**Comment by SladeHazard** [comment]
New error with the same one this time this error occured on playerjoinevent:https://hastebin.com/igewopupov.md

**Comment by SladeHazard** [comment]
update: to reproduce load chunks error happens when i do /warp b or /warp c when new chunks load

**Comment by Nort721** [comment]
recent changes may solve this one, if it happens again to make sure to make a report using a newer version, will try solving it faster this time if it happens again
